#Java mappings for Pkl module `ba.sake.deder.examples.plugins.hello`
#Tue Jun 09 18:25:51 CEST 2026
org.pkl.config.java.mapper.ba.sake.deder.examples.plugins.hello\#HelloPlugin=ba.sake.deder.examples.plugins.Hello$HelloPlugin
org.pkl.config.java.mapper.ba.sake.deder.examples.plugins.hello\#HelloPluginConfig=ba.sake.deder.examples.plugins.Hello$HelloPluginConfig
org.pkl.config.java.mapper.ba.sake.deder.examples.plugins.hello\#ModuleClass=ba.sake.deder.examples.plugins.Hello
