tutorials:
  - label: "Installation"
    url: "/tutorials/installation.html"
  - label: "Quickstart"
    url: "/tutorials/quickstart.html"
  - label: "Packaging"
    url: "/tutorials/packaging.html"
  - label: "Publishing"
    url: "/tutorials/publishing.html"
  - label: "Scala.js"
    url: "/tutorials/scalajs.html"
  - label: "Scala Native"
    url: "/tutorials/scalanative.html"
  - label: "Cross Project"
    url: "/tutorials/cross-project.html"
  

references:
  - label: "Cheatsheet"
    url: "/reference/cheatsheet.html"
  - label: "Architecture"
    url: "/reference/architecture.html"
  - label: "Task caching"
    url: "/reference/caching.html"
  - label: "Files layout"
    url: "/reference/files-layout.html"
  - label: "Server Properties"
    url: "/reference/server-properties.html"
  - label: "Repositories"
    url: "/reference/repositories.html"
  - label: "Testing"
    url: "/reference/testing.html"

howtos:
  - label: "Adding dependencies"
    url: "/howtos/dependencies.html"
  - label: "Environment variables and JVM options"
    url: "/howtos/env-vars.html"
  - label: "Invoking Maven applications"
    url: "/howtos/mvn-apps.html"
  - label: "OTEL tracing/logging/metrics"
    url: "/howtos/otel.html"

philosophies:
  - label: "Design Philosophy"
    url: "/philosophy/design.html"
  - label: "Why Pkl?"
    url: "/philosophy/why-pkl.html"
