tutorials:
  - label: "Installation"
    url: "/tutorials/installation.html"
  - label: "Quickstart"
    url: "/tutorials/quickstart.html"
  - label: "Scala.js"
    url: "/tutorials/scalajs.html"
  - label: "Scala Native"
    url: "/tutorials/scalanative.html"
  - label: "Cross Project"
    url: "/tutorials/cross-project.html"
  - label: "Publishing"
    url: "/tutorials/publishing.html"

references:
  - label: "Architecture"
    url: "/reference/architecture.html"
  - label: "Files layout"
    url: "/reference/files-layout.html"

philosophies:
  - label: "Design Philosophy"
    url: "/philosophy/design.html"
  - label: "Why Pkl?"
    url: "/philosophy/why-pkl.html"
