package ba.sake.deder

import java.io.File
import scala.jdk.CollectionConverters.*
import scala.util.Using
import com.typesafe.scalalogging.StrictLogging
import dependency.ScalaVersion
import ba.sake.deder.zinc.{DederZincLogger, JdkUtils, ZincCompilersCache}
import ba.sake.deder.config.DederProject.{
  JavaModule,
  JavaTestModule,
  ModuleType,
  ScalaJsModule,
  ScalaJsTestModule,
  ScalaModule,
  ScalaNativeModule,
  ScalaNativeTestModule,
  ScalaTestModule
}
import ba.sake.deder.config.DederProject
import ba.sake.deder.deps.Dependency
import ba.sake.deder.deps.given
import ba.sake.deder.testing.*
import ba.sake.deder.testing.forked.ForkedTestOrchestrator
import ba.sake.deder.testing.inmemory.InMemoryTestOrchestrator

class CoreTasks() extends StrictLogging {

  /** source folders */
  val sourcesTask = SourceFilesTask(
    name = "sources",
    execute = { ctx =>
      val sources = ctx.module match {
        case m: JavaModule => m.sources.asScala.toSeq
        case _             => Seq.empty
      }
      sources.map(s => DederPath(os.SubPath(s"${ctx.module.root}/${s}")))
    },
    description = "Source folders of the module"
  )

  val sourceFilesTask = CachedTaskBuilder
    .make[Seq[DederPath]](
      name = "sourceFiles"
    )
    .dependsOn(sourcesTask)
    .build { ctx =>
      val sourceDirs = ctx.depResults._1
      sourceDirs
        .map(_.absPath)
        .flatMap { sourceDir =>
          if os.exists(sourceDir) then
            os.walk(
              sourceDir,
              skip = p => {
                if os.isDir(p) then false
                else if os.isFile(p) then !(p.ext == "scala" || p.ext == "java")
                else true
              }
            )
          else Seq.empty
        }
        .filter(os.isFile)
        .map(DederPath(_))
    }

  // sources generated by annotation processors
  val generatedSourcesTask = TaskBuilder
    .make[os.Path](
      name = "generatedSources"
    )
    .build { ctx => ctx.out }

  /** resource folders */
  val resourcesTask = SourceFilesTask(
    name = "resources",
    execute = { ctx =>
      val resources = ctx.module match {
        case m: JavaModule => m.resources.asScala.toSeq
        case _             => Seq.empty
      }
      resources.map(s => DederPath(os.SubPath(s"${ctx.module.root}/${s}")))
    }
  )

  val javaHomeTask = ConfigValueTask[Option[os.Path]](
    name = "javaHome",
    execute = { ctx =>
      ctx.module match {
        case m: JavaModule => Option(m.javaHome).map(p => os.Path(p))
        case _             => None
      }
    }
  )

  val javaVersionTask = ConfigValueTask[Option[String]](
    name = "javaVersion",
    execute = { ctx =>
      ctx.module match {
        case m: JavaModule => Option(m.javaVersion)
        case _             => None
      }
    }
  )

  val javacOptionsTask = ConfigValueTask[Seq[String]](
    name = "javacOptions",
    execute = { ctx =>
      ctx.module match {
        case m: JavaModule => m.javacOptions.asScala.toSeq
        case _             => Seq.empty
      }
    }
  )

  val scalacOptionsTask = ConfigValueTask[Seq[String]](
    name = "scalacOptions",
    execute = { ctx =>
      ctx.module match {
        case m: ScalaModule => m.scalacOptions.asScala.toSeq
        case _              => Seq.empty
      }
    }
  )

  val scalaVersionTask = ConfigValueTask[String](
    name = "scalaVersion",
    execute = { ctx =>
      ctx.module match {
        case m: ScalaModule => m.scalaVersion
        case _              => "2.13.17" // dummy default scala version
      }
    }
  )

  val depsTask = ConfigValueTask[Seq[String]](
    name = "deps",
    execute = { ctx =>
      ctx.module match {
        case m: JavaModule => m.deps.asScala.toSeq
        case _             => Seq.empty
      }
    }
  )

  // applied deps, with scala version resolved
  val dependenciesTask = CachedTaskBuilder
    .make[Seq[deps.Dependency]](
      name = "dependencies"
    )
    .dependsOn(depsTask)
    .dependsOn(scalaVersionTask)
    .build { ctx =>
      val (deps, scalaVersion) = ctx.depResults
      val platformSuffix = ctx.module match {
        case m: ScalaJsModule     => ScalaVersion.jsBinary(m.scalaJsVersion).map("sjs" + _)
        case m: ScalaNativeModule => ScalaVersion.nativeBinary(m.scalaNativeVersion).map("native" + _)
        case _                    => None
      }
      deps.map(depDecl => Dependency.make(depDecl, scalaVersion, platformSuffix))
    }

  val allDependenciesTask = CachedTaskBuilder
    .make[Seq[deps.Dependency]](
      name = "allDependencies",
      transitive = true
    )
    .dependsOn(dependenciesTask)
    .build { ctx =>
      val deps = ctx.depResults._1
      (deps ++ ctx.transitiveResults.flatten.flatten).distinct
    }

  val mandatoryDependenciesTask = CachedTaskBuilder
    .make[Seq[deps.Dependency]](
      name = "mandatoryDependencies"
    )
    .dependsOn(scalaVersionTask)
    .build { ctx =>
      val scalaVersion = ctx.depResults._1
      val scalaLibDeps =
        if scalaVersion.startsWith("3.") then
          ctx.module match {
            case m: ScalaJsTestModule =>
              Seq(
                Dependency.make(
                  s"org.scala-lang::scala3-library::${scalaVersion}",
                  scalaVersion,
                  ScalaVersion.jsBinary(m.scalaJsVersion).map("sjs" + _)
                ),
                Dependency.make(
                  s"org.scala-js::scalajs-library:${m.scalaJsVersion}",
                  if m.scalaVersion.startsWith("3.") then "2.13" else m.scalaVersion
                ),
                Dependency.make(
                  s"org.scala-js::scalajs-test-bridge:${m.scalaJsVersion}",
                  if m.scalaVersion.startsWith("3.") then "2.13" else m.scalaVersion
                )
              )
            case m: ScalaJsModule =>
              Seq(
                Dependency.make(
                  s"org.scala-lang::scala3-library::${scalaVersion}",
                  scalaVersion,
                  ScalaVersion.jsBinary(m.scalaJsVersion).map("sjs" + _)
                ),
                Dependency.make(
                  s"org.scala-js::scalajs-library:${m.scalaJsVersion}",
                  if m.scalaVersion.startsWith("3.") then "2.13" else m.scalaVersion
                )
              )
            case m: ScalaNativeModule =>
              val scalaSpecificVersion = s"${scalaVersion}+${m.scalaNativeVersion}"
              Seq(
                Dependency.make(s"org.scala-lang::scala3-library:${scalaVersion}", scalaVersion),
                Dependency.make(
                  s"org.scala-native::scala3lib::${scalaSpecificVersion}",
                  scalaVersion,
                  ScalaVersion.nativeBinary(m.scalaNativeVersion).map("native" + _)
                ),
                Dependency.make(
                  s"org.scala-native::scalalib::${scalaSpecificVersion}",
                  scalaVersion,
                  ScalaVersion.nativeBinary(m.scalaNativeVersion).map("native" + _)
                ),
                Dependency.make(
                  s"org.scala-native::javalib::${m.scalaNativeVersion}",
                  scalaVersion,
                  ScalaVersion.nativeBinary(m.scalaNativeVersion).map("native" + _)
                ),
                Dependency.make(
                  s"org.scala-native::nativelib::${m.scalaNativeVersion}",
                  scalaVersion,
                  ScalaVersion.nativeBinary(m.scalaNativeVersion).map("native" + _)
                ),
                Dependency.make(
                  s"org.scala-native::auxlib::${m.scalaNativeVersion}",
                  scalaVersion,
                  ScalaVersion.nativeBinary(m.scalaNativeVersion).map("native" + _)
                ),
                Dependency.make(
                  s"org.scala-native::clib::${m.scalaNativeVersion}",
                  scalaVersion,
                  ScalaVersion.nativeBinary(m.scalaNativeVersion).map("native" + _)
                ),
                Dependency.make(
                  s"org.scala-native::posixlib::${m.scalaNativeVersion}",
                  scalaVersion,
                  ScalaVersion.nativeBinary(m.scalaNativeVersion).map("native" + _)
                )
              )
            case m: ScalaModule => Seq(Dependency.make(s"org.scala-lang::scala3-library:${scalaVersion}", scalaVersion))
            case _              => Seq.empty
          }
        else
          ctx.module match {
            case m: ScalaJsTestModule =>
              Seq(
                Dependency.make(
                  s"org.scala-lang:scala-library:${scalaVersion}",
                  scalaVersion,
                  ScalaVersion.jsBinary(m.scalaJsVersion).map("sjs" + _)
                ),
                Dependency.make(
                  s"org.scala-js::scalajs-library:${m.scalaJsVersion}",
                  if m.scalaVersion.startsWith("3.") then "2.13" else m.scalaVersion
                ),
                Dependency.make(
                  s"org.scala-js::scalajs-test-bridge:${m.scalaJsVersion}",
                  if m.scalaVersion.startsWith("3.") then "2.13" else m.scalaVersion
                )
              )
            case m: ScalaJsModule =>
              Seq(
                Dependency.make(
                  s"org.scala-lang:scala-library:${scalaVersion}",
                  scalaVersion,
                  ScalaVersion.jsBinary(m.scalaJsVersion).map("sjs" + _)
                ),
                Dependency.make(
                  s"org.scala-js::scalajs-library:${m.scalaJsVersion}",
                  if m.scalaVersion.startsWith("3.") then "2.13" else m.scalaVersion
                )
              )
            case m: ScalaNativeModule =>
              val scalaSpecificVersion = s"${scalaVersion}+${m.scalaNativeVersion}"
              Seq(
                Dependency.make(s"org.scala-lang:scala-library:${scalaVersion}", scalaVersion),
                Dependency.make(
                  s"org.scala-native::scalalib::${scalaSpecificVersion}",
                  scalaVersion,
                  ScalaVersion.nativeBinary(m.scalaNativeVersion).map("native" + _)
                ),
                Dependency.make(
                  s"org.scala-native::javalib::${m.scalaNativeVersion}",
                  scalaVersion,
                  ScalaVersion.nativeBinary(m.scalaNativeVersion).map("native" + _)
                ),
                Dependency.make(
                  s"org.scala-native::nativelib::${m.scalaNativeVersion}",
                  scalaVersion,
                  ScalaVersion.nativeBinary(m.scalaNativeVersion).map("native" + _)
                ),
                Dependency.make(
                  s"org.scala-native::auxlib::${m.scalaNativeVersion}",
                  scalaVersion,
                  ScalaVersion.nativeBinary(m.scalaNativeVersion).map("native" + _)
                ),
                Dependency.make(
                  s"org.scala-native::clib::${m.scalaNativeVersion}",
                  scalaVersion,
                  ScalaVersion.nativeBinary(m.scalaNativeVersion).map("native" + _)
                ),
                Dependency.make(
                  s"org.scala-native::posixlib::${m.scalaNativeVersion}",
                  scalaVersion,
                  ScalaVersion.nativeBinary(m.scalaNativeVersion).map("native" + _)
                )
              )
            case m: ScalaModule => Seq(Dependency.make(s"org.scala-lang:scala-library:${scalaVersion}", scalaVersion))
            case _              => Seq.empty
          }
      scalaLibDeps
    }

  val classesTask = TaskBuilder
    .make[os.Path](
      name = "classes"
    )
    .build { ctx => ctx.out }

  val semanticdbDirTask = TaskBuilder
    .make[os.Path](
      name = "semanticdb"
    )
    .build { ctx => ctx.out }

  // this is localRunClasspath in mill ??
  val allClassesDirsTask = CachedTaskBuilder
    .make[Seq[os.Path]](
      name = "allClassesDirs",
      transitive = true
    )
    .dependsOn(classesTask)
    .build { ctx =>
      Seq(ctx.depResults._1) ++ ctx.transitiveResults.flatten.flatten.reverse.distinct.reverse
    }

  val compileClasspathTask = CachedTaskBuilder
    .make[Seq[os.Path]](
      name = "compileClasspath",
      transitive = true
    )
    .dependsOn(scalaVersionTask)
    .dependsOn(mandatoryDependenciesTask)
    .dependsOn(allDependenciesTask)
    .dependsOn(allClassesDirsTask)
    .build { ctx =>
      // we feed even this module's classes dir because of javac annotation processing,
      // it can generate java sources.. and then scala sources can depend on them
      val (scalaVersion, mandatoryDependencies, dependencies, allClassesDirs) = ctx.depResults
      val depsJars = ctx.dependencyResolver
        .fetchFiles(mandatoryDependencies ++ dependencies, Some(ctx.notifications))
      (allClassesDirs ++ depsJars).reverse.distinct.reverse
    }

  val javaSemanticdbVersionTask = ConfigValueTask[String](
    name = "javaSemanticdbVersion",
    execute = { ctx =>
      ctx.module match {
        case m: JavaModule => m.javaSemanticdbVersion
        case _             => "0.11.1"
      }
    }
  )

  val scalaSemanticdbVersionTask = CachedTaskBuilder
    .make[String](
      name = "scalaSemanticdbVersion"
    )
    .dependsOn(scalaVersionTask)
    .build { ctx =>
      val scalaVersion = ctx.depResults._1
      ctx.module match {
        case m: ScalaModule =>
          Option(m.scalaSemanticdbVersion).getOrElse {
            scalaVersion match {
              case s"2.13.${minor}" =>
                val minorNum = minor.toInt
                if minorNum == 1 then "4.6.0"
                else if minorNum < 8 then "4.8.4"
                else if minorNum == 8 then "4.8.9"
                else if minorNum == 9 then "4.9.0"
                else if minorNum == 10 then "4.9.3"
                else if minorNum == 11 then "4.9.9"
                else if minorNum == 12 then "4.12.3"
                else if minorNum == 13 then "4.13.9"
                else if minorNum == 14 then "4.14.1"
                else "4.14.5"
              case _ => "4.14.5"
            }
          }
        case _ => "4.14.5"
      }
    }

  val semanticdbEnabledTask = ConfigValueTask[Boolean](
    name = "semanticdbEnabled",
    execute = { ctx =>
      ctx.module match {
        case m: JavaModule => m.semanticdbEnabled
        case _             => false
      }
    }
  )

  val javacAnnotationProcessorDepsTask = ConfigValueTask[Seq[String]](
    name = "javacAnnotationProcessorDeps",
    execute = { ctx =>
      ctx.module match {
        case m: JavaModule => m.javacAnnotationProcessorDeps.asScala.toSeq
        case _             => Seq.empty
      }
    }
  )

  val javacAnnotationProcessorsTask = CachedTaskBuilder
    .make[Seq[os.Path]](
      name = "javacAnnotationProcessors"
    )
    .dependsOn(scalaVersionTask)
    .dependsOn(javacAnnotationProcessorDepsTask)
    .build { ctx =>
      val (scalaVersion, javacAnnotationProcessorDeps) = ctx.depResults
      val processorJars = ctx.dependencyResolver.fetchFiles(
        javacAnnotationProcessorDeps.map(d => Dependency.make(d, scalaVersion)),
        Some(ctx.notifications)
      )
      processorJars
    }

  val scalacPluginDepsTask = ConfigValueTask[Seq[String]](
    name = "scalacPluginDeps",
    execute = { ctx =>
      ctx.module match {
        case m: ScalaModule => m.scalacPluginDeps.asScala.toSeq
        case _              => Seq.empty
      }
    }
  )

  val scalacPluginsTask = CachedTaskBuilder
    .make[Seq[os.Path]](
      name = "scalacPlugins"
    )
    .dependsOn(scalaVersionTask)
    .dependsOn(scalacPluginDepsTask)
    .build { ctx =>
      val (scalaVersion, scalacPluginDeps) = ctx.depResults
      val scalaPlatformDeps =
        if scalaVersion.startsWith("3.") then
          ctx.module match {
            case m: ScalaNativeModule => Seq(s"org.scala-native:::nscplugin:${m.scalaNativeVersion}")
            case _                    => Seq.empty
          }
        else
          ctx.module match {
            case m: ScalaJsModule     => Seq(s"org.scala-js:::scalajs-compiler:${m.scalaJsVersion}")
            case m: ScalaNativeModule => Seq(s"org.scala-native:::nscplugin:${m.scalaNativeVersion}")
            case _                    => Seq.empty
          }
      val allDeps = scalacPluginDeps ++ scalaPlatformDeps
      val allJars = ctx.dependencyResolver.fetchFiles(
        allDeps.map(d => Dependency.make(d, scalaVersion)),
        Some(ctx.notifications)
      )
      // Only pass JARs that are actual compiler plugins (contain plugin.properties).
      // Coursier resolves transitive deps regardless; this filters them out.
      allJars.filter { jar =>
        scala.util.Try {
          val zf = new java.util.zip.ZipFile(jar.toIO)
          try zf.getEntry("plugin.properties") != null
          finally zf.close()
        }.getOrElse(false)
      }
    }

  val compilerDepsTask = CachedTaskBuilder
    .make[Seq[Dependency]](
      name = "compilerDeps"
    )
    .dependsOn(scalaVersionTask)
    .build { ctx =>
      val scalaVersion = ctx.depResults._1
      // TODO scalajs compiler on scala2?
      val compilerDeps =
        if scalaVersion.startsWith("3.") then
          ctx.module match {
            case m: ScalaJsModule =>
              Seq(
                Dependency.make(s"org.scala-lang::scala3-compiler:${scalaVersion}", scalaVersion)
              )
            case _ =>
              Seq(Dependency.make(s"org.scala-lang::scala3-compiler:${scalaVersion}", scalaVersion))
          }
        else
          ctx.module match {
            case _ =>
              Seq(
                Dependency.make(s"org.scala-lang:scala-compiler:${scalaVersion}", scalaVersion),
                Dependency.make(s"org.scala-lang:scala-reflect:${scalaVersion}", scalaVersion)
              )
          }
      compilerDeps
    }

  val compilerJarsTask = CachedTaskBuilder
    .make[Seq[os.Path]](
      name = "compilerJars"
    )
    .dependsOn(compilerDepsTask)
    .build { ctx =>
      val compilerDeps = ctx.depResults._1
      ctx.dependencyResolver.fetchFiles(compilerDeps)
    }

  // returns classes dir
  val compileTask = TaskBuilder
    .make[DederPath](
      name = "compile",
      transitive = true
    )
    .dependsOn(sourceFilesTask)
    .dependsOn(generatedSourcesTask)
    .dependsOn(javaHomeTask)
    .dependsOn(javaVersionTask)
    .dependsOn(javacOptionsTask)
    .dependsOn(scalacOptionsTask)
    .dependsOn(scalaVersionTask)
    .dependsOn(compilerJarsTask)
    .dependsOn(compileClasspathTask)
    .dependsOn(semanticdbDirTask)
    .dependsOn(scalacPluginsTask)
    .dependsOn(javacAnnotationProcessorsTask)
    .dependsOn(javaSemanticdbVersionTask)
    .dependsOn(scalaSemanticdbVersionTask)
    .dependsOn(semanticdbEnabledTask)
    .build { ctx =>
      val (
        sourceFiles,
        generatedSourcesDir,
        javaHome,
        javaVersion,
        javacOptions,
        scalacOptions,
        scalaVersion,
        compilerJars,
        compileClasspath,
        semanticdbDir,
        scalacPlugins,
        javacAnnotationProcessors,
        javaSemanticdbVersion,
        scalaSemanticdbVersion,
        semanticdbEnabled
      ) = ctx.depResults
      // classesTask is NOT a dep here: its outputHash reflects compiled class contents,
      // which changes after every compilation — making the cache key self-referential.
      // The path is stable and derived the same way classesTask would compute it.
      val classesDir = ctx.out / os.up / "classes"

      JdkUtils.checkCompat(JdkUtils.getVersion(scala.util.Properties.javaSpecVersion), scalaVersion)

      // annotation processors need generated sources dir to exist
      os.makeDir.all(generatedSourcesDir)

      val zincCacheFile = ctx.out / "inc_compile.zip"
      val zincLogger = new DederZincLogger(ctx.notifications, ctx.module.id)

      // semanticdb javac annotation processor (when enabled)
      val semanticdbJavacJar =
        if semanticdbEnabled then
          ctx.dependencyResolver.fetchFiles(
            Seq(Dependency.make(s"com.sourcegraph:semanticdb-javac:${javaSemanticdbVersion}", scalaVersion))
          )
        else Seq.empty
      val allJavacAnnotationProcessors = javacAnnotationProcessors ++ semanticdbJavacJar

      val finalJavacOptions = javacOptions ++
        Option
          .when(allJavacAnnotationProcessors.nonEmpty)(
            Seq(
              "-s",
              generatedSourcesDir.toString,
              "-processorpath",
              allJavacAnnotationProcessors.map(_.toString).mkString(File.pathSeparator)
            )
          )
          .toSeq
          .flatten ++
        javaVersion.map(v => Seq("--release", v)).getOrElse(Seq.empty) ++
        // https://github.com/sourcegraph/scip-java/issues/390
        Option.when(semanticdbEnabled)(
          s"-Xplugin:semanticdb -sourceroot:${DederGlobals.projectRootDir} -targetroot:${semanticdbDir} -build-tool:sbt"
        )

      // For Scala 2: add semanticdb-scalac plugin (when enabled)
      val semanticdbScalacJar =
        if semanticdbEnabled && !scalaVersion.startsWith("3.") then
          ctx.dependencyResolver.fetchFiles(
            Seq(Dependency.make(s"org.scalameta:::semanticdb-scalac:${scalaSemanticdbVersion}", scalaVersion))
          )
        else Seq.empty
      val allScalacPlugins = scalacPlugins ++ semanticdbScalacJar

      val semanticDbScalacOpts =
        if !semanticdbEnabled then Seq.empty
        else if scalaVersion.startsWith("3.") then
          Seq(
            "-Xsemanticdb",
            "-sourceroot",
            DederGlobals.projectRootDir.toString,
            "-semanticdb-target",
            semanticdbDir.toString
          )
        else
          Seq(
            "-Yrangepos",
            s"-P:semanticdb:sourceroot:${DederGlobals.projectRootDir}",
            s"-P:semanticdb:targetroot:${semanticdbDir}"
          )
      val platformSpecificScalacOptions = ctx.module match {
        case module: ScalaJsModule => if scalaVersion.startsWith("3.") then Seq("-scalajs") else Seq.empty
        case _                     => Seq.empty
      }
      val finalScalacOptions =
        scalacOptions ++ allScalacPlugins
          .map(p => s"-Xplugin:${p.toString}") ++ platformSpecificScalacOptions ++ semanticDbScalacOpts

      ZincCompilersCache
        .get(scalaVersion, ctx.dependencyResolver)
        .compile(
          javaHome = javaHome.map(_.toNIO),
          scalaVersion = scalaVersion,
          compilerJars = compilerJars,
          compileClasspath = compileClasspath,
          zincCacheFile = zincCacheFile,
          sources = sourceFiles.map(_.absPath),
          classesDir = classesDir,
          scalacOptions = finalScalacOptions,
          javacOptions = finalJavacOptions,
          zincLogger = zincLogger,
          moduleId = ctx.module.id,
          notifications = ctx.notifications
        )
      DederPath(classesDir)
    }

  val jvmOptionsTask = ConfigValueTask[Seq[String]](
    name = "jvmOptions",
    execute = { ctx =>
      ctx.module match {
        case m: JavaModule => m.jvmOptions.asScala.toSeq
        case _             => Seq.empty
      }
    }
  )

  val runClasspathTask = CachedTaskBuilder
    .make[Seq[os.Path]](
      name = "runClasspath",
      transitive = true
    )
    .dependsOn(compileTask)
    .dependsOn(compileClasspathTask)
    .dependsOn(resourcesTask)
    .build { ctx =>
      val (_, compileClasspath, resourceDirs) = ctx.depResults
      val resources = resourceDirs.map(_.absPath)
      val localRunClasspath = compileClasspath ++ resources
      (localRunClasspath ++ ctx.transitiveResults.flatten.flatten).reverse.distinct.reverse
    }

  val mainClassesTask = CachedTaskBuilder
    .make[Seq[String]](
      name = "mainClasses"
    )
    .dependsOn(compileTask)
    .dependsOn(classesTask)
    .build { ctx =>
      val (_, classesDir) = ctx.depResults
      MainClassesDiscovery.discover(Seq(classesDir))
    }

  val mainClassTask = ConfigValueTask[Option[String]](
    name = "mainClass",
    execute = { ctx =>
      ctx.module match {
        case m: JavaModule => Option(m.mainClass)
        case _             => None
      }
    }
  )

  val finalMainClassTask = CachedTaskBuilder
    .make[Option[String]](
      name = "finalMainClass"
    )
    .dependsOn(mainClassTask)
    .dependsOn(mainClassesTask)
    .build { ctx =>
      val (mainClass, discoveredMainClasses) = ctx.depResults
      mainClass
        .orElse {
          Option.when(discoveredMainClasses.length == 1)(discoveredMainClasses.head)
        }
    }

  val runTask = TaskBuilder
    .make[Seq[String]](
      name = "run",
      singleton = true
    )
    .dependsOn(runClasspathTask)
    .dependsOn(mainClassesTask)
    .dependsOn(finalMainClassTask)
    .dependsOn(jvmOptionsTask)
    .build { ctx =>
      val (runClasspath, discoveredMainClasses, finalMainClass, jvmOptions) = ctx.depResults
      finalMainClass match {
        case Some(mc) =>
          val cp = runClasspath.map(_.toString)
          val cmd = Seq("java") ++ jvmOptions ++ Seq("-cp", cp.mkString(File.pathSeparator), mc) ++ ctx.args
          logger.debug(s"Client should run command: ${cmd}")
          val forkEnv = ctx.module match {
            case m: JavaModule => m.forkEnv.asScala.to(Map)
            case _             => Map.empty
          }
          ctx.notifications.add(ServerNotification.RunSubprocess(cmd, forkEnv, ctx.watch))
          cmd
        case None =>
          if discoveredMainClasses.length > 1 then
            throw new Exception(
              s"Multiple main classes discovered for module '${ctx.module.id}': ${discoveredMainClasses.mkString(", ")}. " +
                "Please specify which one to run in deder.pkl or use runMain task with main class argument."
            )
          else throw new Exception(s"No main class specified for module: ${ctx.module.id}")
      }
    }

  val runMainTask = TaskBuilder
    .make[Seq[String]](
      name = "runMain",
      singleton = true
    )
    .dependsOn(runClasspathTask)
    .dependsOn(mainClassesTask)
    .dependsOn(jvmOptionsTask)
    .build { ctx =>
      val (runClasspath, discoveredMainClasses, jvmOptions) = ctx.depResults
      val selectedMainClass = ctx.args.headOption.getOrElse(
        throw RuntimeException(
          "No main class specified to run. Please provide the main class as an argument. " +
            s"Possible candidates: ${discoveredMainClasses.mkString(", ")}"
        )
      )
      val finalMainClass = discoveredMainClasses.find(_ == selectedMainClass)
      finalMainClass match {
        case Some(mc) =>
          val cp = runClasspath.map(_.toString)
          val cmd = Seq("java") ++ jvmOptions ++ Seq("-cp", cp.mkString(File.pathSeparator), mc) ++ ctx.args.tail
          logger.debug(s"Client should run command: ${cmd}")
          val forkEnv = ctx.module match {
            case m: JavaModule => m.forkEnv.asScala.to(Map)
            case _             => Map.empty
          }
          ctx.notifications.add(ServerNotification.RunSubprocess(cmd, forkEnv, ctx.watch))
          cmd
        case None =>
          throw new RuntimeException(
            s"Class '${selectedMainClass}' with main method not found for module '${ctx.module.id}'. " +
              s"Possible candidates: ${discoveredMainClasses.mkString(", ")}"
          )
      }
    }

  val runMvnAppTask = TaskBuilder
    .make[Seq[String]](
      name = "runMvnApp"
    )
    .dependsOn(sourcesTask)
    .dependsOn(scalaVersionTask)
    .dependsOn(jvmOptionsTask)
    .build { ctx =>
      val (sources, scalaVersion, jvmOptions) = ctx.depResults
      val sourcePaths = sources.map(_.absPath).filter(os.exists(_)).map(_.toString)

      val userMvnAppsMap: Map[String, DederProject.MvnApp] = ctx.module match {
        case m: JavaModule => m.mvnApps.asScala.toMap
        case _             => Map.empty
      }
      val autoMvnAppsMap: Map[String, DederProject.MvnApp] = ctx.module match {
        case m: ScalaModule =>
          val scalafmtDep = "org.scalameta:scalafmt-cli_2.13:3.10.7"
          val scalafmtMain = "org.scalafmt.cli.Cli"
          Map(
            "fmt" -> DederProject.MvnApp(scalafmtDep, scalafmtMain, sourcePaths.asJava),
            "fmtCheck" -> DederProject.MvnApp(scalafmtDep, scalafmtMain, (Seq("--check") ++ sourcePaths).asJava)
          )
        case _ => Map.empty
      }
      val effectiveMap = (userMvnAppsMap ++ autoMvnAppsMap).map { case (name, tc) =>
        name -> (tc.dep, tc.mainClass, tc.args.asScala.toSeq)
      }

      val mvnAppName = ctx.args.headOption.getOrElse(
        throw new RuntimeException(
          s"No maven app name specified. Available maven apps: ${effectiveMap.keys.mkString(", ")}"
        )
      )
      effectiveMap.get(mvnAppName) match {
        case Some((dep, mainClass, args)) =>
          val dependency = Dependency.make(dep, scalaVersion)
          val jars = ctx.dependencyResolver.fetchFiles(Seq(dependency), Some(ctx.notifications))
          val cp = jars.map(_.toString).mkString(File.pathSeparator)
          val commandArgs = args ++ ctx.args.tail
          val cmd = Seq("java") ++ jvmOptions ++ Seq("-cp", cp, mainClass) ++ commandArgs
          logger.info(s"Running maven app '${mvnAppName}': ${cmd}")
          val forkEnv = ctx.module match {
            case m: JavaModule => m.forkEnv.asScala.to(Map)
            case _             => Map.empty
          }
          ctx.notifications.add(ServerNotification.RunSubprocess(cmd, forkEnv, false))
          cmd
        case _ =>
          throw new RuntimeException(
            s"Maven app '${mvnAppName}' not found for module '${ctx.module.id}'. " +
              s"Available maven apps: ${effectiveMap.keys.mkString(", ")}"
          )
      }
    }

  val fixTask = TaskBuilder
    .make[Seq[String]](
      name = "fix",
      supportedModuleTypes = Set(
        ModuleType.SCALA,
        ModuleType.SCALA_TEST,
        ModuleType.SCALA_JS,
        ModuleType.SCALA_JS_TEST,
        ModuleType.SCALA_NATIVE,
        ModuleType.SCALA_NATIVE_TEST
      )
    )
    .dependsOn(sourcesTask)
    .dependsOn(scalaVersionTask)
    .dependsOn(scalacOptionsTask)
    .dependsOn(jvmOptionsTask)
    .dependsOn(compileTask)
    .dependsOn(compileClasspathTask)
    .dependsOn(semanticdbDirTask)
    .build { ctx =>
      val (sources, scalaVersion, scalacOptions, jvmOptions, _, compileClasspath, semanticdbDir) = ctx.depResults
      val dependency = Dependency.make(ScalafixUtils.scalafixDep(scalaVersion), scalaVersion)
      val jars = ctx.dependencyResolver.fetchFiles(Seq(dependency), Some(ctx.notifications))
      val cp = jars.map(_.toString).mkString(File.pathSeparator)
      val sourcePaths = sources.map(_.absPath).filter(os.exists(_)).map(_.toString)
      val scalafixArgs =
        ScalafixUtils.buildArgs(scalaVersion, scalacOptions, compileClasspath, semanticdbDir, sourcePaths, ctx.args)
      val cmd = Seq("java") ++ jvmOptions ++ Seq("-cp", cp, "scalafix.cli.Cli") ++ scalafixArgs
      logger.info(s"Running scalafix fix: ${cmd}")
      val forkEnv = ctx.module match {
        case m: JavaModule => m.forkEnv.asScala.to(Map)
        case _             => Map.empty
      }
      ctx.notifications.add(ServerNotification.RunSubprocess(cmd, forkEnv, ctx.watch))
      cmd
    }

  val fixCheckTask = TaskBuilder
    .make[Seq[String]](
      name = "fixCheck",
      supportedModuleTypes = Set(
        ModuleType.SCALA,
        ModuleType.SCALA_TEST,
        ModuleType.SCALA_JS,
        ModuleType.SCALA_JS_TEST,
        ModuleType.SCALA_NATIVE,
        ModuleType.SCALA_NATIVE_TEST
      )
    )
    .dependsOn(sourcesTask)
    .dependsOn(scalaVersionTask)
    .dependsOn(scalacOptionsTask)
    .dependsOn(jvmOptionsTask)
    .dependsOn(compileTask)
    .dependsOn(compileClasspathTask)
    .dependsOn(semanticdbDirTask)
    .build { ctx =>
      val (sources, scalaVersion, scalacOptions, jvmOptions, _, compileClasspath, semanticdbDir) = ctx.depResults
      val dependency = Dependency.make(ScalafixUtils.scalafixDep(scalaVersion), scalaVersion)
      val jars = ctx.dependencyResolver.fetchFiles(Seq(dependency), Some(ctx.notifications))
      val cp = jars.map(_.toString).mkString(File.pathSeparator)
      val sourcePaths = sources.map(_.absPath).filter(os.exists(_)).map(_.toString)
      val scalafixArgs = ScalafixUtils.buildArgs(
        scalaVersion,
        scalacOptions,
        compileClasspath,
        semanticdbDir,
        sourcePaths,
        Seq("--test") ++ ctx.args
      )
      val cmd = Seq("java") ++ jvmOptions ++ Seq("-cp", cp, "scalafix.cli.Cli") ++ scalafixArgs
      logger.info(s"Running scalafix fixCheck: ${cmd}")
      val forkEnv = ctx.module match {
        case m: JavaModule => m.forkEnv.asScala.to(Map)
        case _             => Map.empty
      }
      ctx.notifications.add(ServerNotification.RunSubprocess(cmd, forkEnv, false))
      cmd
    }

  val testClassesTask = CachedTaskBuilder
    .make[Seq[DiscoveredFrameworkTests]](
      name = "testClasses",
      supportedModuleTypes = Set(
        ModuleType.JAVA_TEST,
        ModuleType.SCALA_TEST,
        ModuleType.SCALA_JS_TEST,
        ModuleType.SCALA_NATIVE_TEST
      )
    )
    .dependsOn(classesTask)
    .dependsOn(runClasspathTask)
    .build { ctx =>
      val (classesDir, runClasspath) = ctx.depResults
      val runtimeClasspath = (Seq(classesDir) ++ runClasspath).reverse.distinct.reverse
      ClassLoaderUtils.withTestsClassLoader(runtimeClasspath) { classLoader =>
        val frameworkClassNames = ctx.module match {
          case m: JavaTestModule        => m.testFrameworks.asScala.toSeq
          case m: ScalaTestModule       => m.testFrameworks.asScala.toSeq
          case m: ScalaJsTestModule     => m.testFrameworks.asScala.toSeq
          case m: ScalaNativeTestModule => m.testFrameworks.asScala.toSeq
          case _                        => Seq.empty
        }
        val testDiscovery = DederTestDiscovery(
          classLoader = classLoader,
          testClassesDir = classesDir,
          testClasspath = runtimeClasspath,
          frameworkClassNames = frameworkClassNames,
          logger = DederTestLogger(ctx.notifications, ctx.module.id)
        )
        testDiscovery.discover()
      }
    }

  val testTask = TaskBuilder
    .make[DederTestResults](
      name = "test",
      supportedModuleTypes = Set(ModuleType.JAVA_TEST, ModuleType.SCALA_TEST)
    )
    .dependsOn(runClasspathTask)
    .dependsOn(jvmOptionsTask)
    .dependsOn(javaHomeTask)
    .dependsOn(testClassesTask)
    .buildWithSummary(
      execute = { ctx =>
        val (runClasspath, jvmOptions, javaHome, discoveredTests) = ctx.depResults
        OutputCaptureContext.withCapture(ctx.notifications, ctx.module.id) {
          val cpus = Runtime.getRuntime.availableProcessors()
          def resolve(n: Int): Int = if n == 0 then cpus else n
          val (forkEnv, testParallelism, maxTestForks) = ctx.module match {
            case m: JavaTestModule =>
              (m.forkEnv.asScala.to(Map), resolve(m.testParallelism.toInt), resolve(m.maxTestForks.toInt))
            case m: ScalaTestModule =>
              (m.forkEnv.asScala.to(Map), resolve(m.testParallelism.toInt), resolve(m.maxTestForks.toInt))
            case _ => (Map.empty, cpus, cpus)
          }
          val testOptions = DederTestOptions(ctx.args)
          val clientEnv = Option(RequestContext.clientParams.get()).map(_.envVars).getOrElse(Map.empty)
          val mergedEnv = clientEnv ++ forkEnv // forkEnv wins on conflict
          val results = ForkedTestOrchestrator.run(
            discoveredTests = discoveredTests,
            runtimeClasspath = runClasspath,
            jvmOptions = jvmOptions,
            envVars = mergedEnv,
            javaHome = javaHome.map(_.toString),
            testOptions = testOptions,
            notifications = ctx.notifications,
            moduleId = ctx.module.id,
            outDir = ctx.out,
            testParallelism = testParallelism,
            maxTestForks = maxTestForks
          )
          JUnitXmlReportWriter.outputDir(ctx.module, ctx.out).foreach(JUnitXmlReportWriter.writeReports(results, _))
          results
        }
      },
      isResultSuccessful = _.success,
      summarize = (results, notifs) => TestResultsSummary.summarize(results.map((m, r) => m.id -> r), notifs)
    )

  val testInMemoryTask = TaskBuilder
    .make[DederTestResults](
      name = "testInMemory",
      supportedModuleTypes = Set(ModuleType.JAVA_TEST, ModuleType.SCALA_TEST)
    )
    .dependsOn(runClasspathTask)
    .dependsOn(testClassesTask)
    .buildWithSummary(
      execute = { ctx =>
        val (runClasspath, discoveredTests) = ctx.depResults
        OutputCaptureContext.withCapture(ctx.notifications, ctx.module.id) {
          val cpus = Runtime.getRuntime.availableProcessors()
          def resolve(n: Int): Int = if n == 0 then cpus else n
          val testParallelism = ctx.module match {
            case m: JavaTestModule  => resolve(m.testParallelism.toInt)
            case m: ScalaTestModule => resolve(m.testParallelism.toInt)
            case _                  => cpus
          }
          val testOptions = DederTestOptions(ctx.args)
          val results = InMemoryTestOrchestrator.run(
            discoveredTests = discoveredTests,
            runtimeClasspath = runClasspath,
            testOptions = testOptions,
            notifications = ctx.notifications,
            moduleId = ctx.module.id,
            testParallelism = testParallelism
          )
          JUnitXmlReportWriter.outputDir(ctx.module, ctx.out).foreach(JUnitXmlReportWriter.writeReports(results, _))
          results
        }
      },
      isResultSuccessful = _.success,
      summarize = (results, notifs) => TestResultsSummary.summarize(results.map((m, r) => m.id -> r), notifs)
    )

  // order matters for dependency resolution!!
  val all: Seq[Task[?, ?]] = Seq(
    sourcesTask,
    sourceFilesTask,
    generatedSourcesTask,
    javaHomeTask,
    javaVersionTask,
    scalaVersionTask,
    resourcesTask,
    javacOptionsTask,
    scalacOptionsTask,
    javaSemanticdbVersionTask,
    scalaSemanticdbVersionTask,
    semanticdbEnabledTask,
    javacAnnotationProcessorDepsTask,
    scalacPluginDepsTask,
    javacAnnotationProcessorsTask,
    scalacPluginsTask,
    depsTask,
    mandatoryDependenciesTask,
    dependenciesTask,
    allDependenciesTask,
    classesTask,
    semanticdbDirTask,
    allClassesDirsTask,
    compilerDepsTask,
    compilerJarsTask,
    compileClasspathTask,
    compileTask,
    jvmOptionsTask,
    runClasspathTask,
    mainClassTask,
    mainClassesTask,
    finalMainClassTask,
    runTask,
    runMainTask,
    runMvnAppTask,
    fixTask,
    fixCheckTask,
    testClassesTask,
    testTask,
    testInMemoryTask
  )

}
