package ba.sake.deder

import javax.tools.ToolProvider
import java.io.File
import scala.jdk.CollectionConverters.*
import scala.util.Using
import com.typesafe.scalalogging.StrictLogging
import dependency.ScalaVersion
import ba.sake.tupson.JsonRW
import ba.sake.deder.testing.OutputCaptureContext
import ba.sake.deder.zinc.{DederZincLogger, JdkUtils, ZincCompilersCache}
import ba.sake.deder.config.DederProject.{
  JavaModule,
  JavaTestModule,
  ModuleType,
  ScalaJsModule,
  ScalaJsTestModule,
  ScalaModule,
  ScalaNativeModule,
  ScalaNativeTestModule,
  ScalaTestModule
}
import ba.sake.deder.config.DederProject
import ba.sake.deder.deps.Dependency
import ba.sake.deder.deps.DependencyResolver
import ba.sake.deder.deps.given
import ba.sake.deder.jar.{JarManifest, JarUtils}
import ba.sake.deder.publish.{GitSemVer, Hasher, PgpSigner, PomGenerator, PomSettings, Publisher}
import ba.sake.deder.scalajs.{ScalaJsLinker, ScalaJsTestRunner}
import ba.sake.deder.scalanative.{ScalaNativeLinker, ScalaNativeTestRunner}
import ba.sake.deder.testing.*
import java.lang.reflect.InvocationTargetException

class CoreTasks() extends StrictLogging {

  /** source folders */
  val sourcesTask = SourceFilesTask(
    name = "sources",
    execute = { ctx =>
      val sources = ctx.module match {
        case m: JavaModule => m.sources.asScala.toSeq
        case _             => Seq.empty
      }
      sources.map(s => DederPath(os.SubPath(s"${ctx.module.root}/${s}")))
    },
    description = "Source folders of the module"
  )

  // sources generated by annotation processors
  val generatedSourcesTask = TaskBuilder
    .make[os.Path](
      name = "generatedSources"
    )
    .build { ctx => ctx.out }

  /** resource folders */
  val resourcesTask = SourceFilesTask(
    name = "resources",
    execute = { ctx =>
      val resources = ctx.module match {
        case m: JavaModule => m.resources.asScala.toSeq
        case _             => Seq.empty
      }
      resources.map(s => DederPath(os.SubPath(s"${ctx.module.root}/${s}")))
    }
  )

  val javaHomeTask = ConfigValueTask[Option[os.Path]](
    name = "javaHome",
    execute = { ctx =>
      ctx.module match {
        case m: JavaModule => Option(m.javaHome).map(p => os.Path(p))
        case _             => None
      }
    }
  )

  val javaVersionTask = ConfigValueTask[Option[String]](
    name = "javaVersion",
    execute = { ctx =>
      ctx.module match {
        case m: JavaModule => Option(m.javaVersion)
        case _             => None
      }
    }
  )

  val javacOptionsTask = ConfigValueTask[Seq[String]](
    name = "javacOptions",
    execute = { ctx =>
      ctx.module match {
        case m: JavaModule => m.javacOptions.asScala.toSeq
        case _             => Seq.empty
      }
    }
  )

  val scalacOptionsTask = ConfigValueTask[Seq[String]](
    name = "scalacOptions",
    execute = { ctx =>
      ctx.module match {
        case m: ScalaModule => m.scalacOptions.asScala.toSeq
        case _              => Seq.empty
      }
    }
  )

  val scalaVersionTask = ConfigValueTask[String](
    name = "scalaVersion",
    execute = { ctx =>
      ctx.module match {
        case m: ScalaModule => m.scalaVersion
        case _              => "2.13.17" // dummy default scala version
      }
    }
  )

  val depsTask = ConfigValueTask[Seq[String]](
    name = "deps",
    execute = { ctx =>
      ctx.module match {
        case m: JavaModule => m.deps.asScala.toSeq
        case _             => Seq.empty
      }
    }
  )

  // applied deps, with scala version resolved
  val dependenciesTask = CachedTaskBuilder
    .make[Seq[deps.Dependency]](
      name = "dependencies"
    )
    .dependsOn(depsTask)
    .dependsOn(scalaVersionTask)
    .build { ctx =>
      val (deps, scalaVersion) = ctx.depResults
      val platformSuffix = ctx.module match {
        case m: ScalaJsModule     => ScalaVersion.jsBinary(m.scalaJsVersion).map("sjs" + _)
        case m: ScalaNativeModule => ScalaVersion.nativeBinary(m.scalaNativeVersion).map("native" + _)
        case _                    => None
      }
      deps.map(depDecl => Dependency.make(depDecl, scalaVersion, platformSuffix))
    }

  val allDependenciesTask = CachedTaskBuilder
    .make[Seq[deps.Dependency]](
      name = "allDependencies",
      transitive = true
    )
    .dependsOn(dependenciesTask)
    .build { ctx =>
      val deps = ctx.depResults._1
      (deps ++ ctx.transitiveResults.flatten.flatten).distinct
    }

  val mandatoryDependenciesTask = CachedTaskBuilder
    .make[Seq[deps.Dependency]](
      name = "mandatoryDependencies"
    )
    .dependsOn(scalaVersionTask)
    .build { ctx =>
      val scalaVersion = ctx.depResults._1
      val scalaLibDeps =
        if scalaVersion.startsWith("3.") then
          ctx.module match {
            case m: ScalaJsTestModule =>
              Seq(
                Dependency.make(
                  s"org.scala-lang::scala3-library::${scalaVersion}",
                  scalaVersion,
                  ScalaVersion.jsBinary(m.scalaJsVersion).map("sjs" + _)
                ),
                Dependency.make(
                  s"org.scala-js::scalajs-library:${m.scalaJsVersion}",
                  if m.scalaVersion.startsWith("3.") then "2.13" else m.scalaVersion
                ),
                Dependency.make(
                  s"org.scala-js::scalajs-test-bridge:${m.scalaJsVersion}",
                  if m.scalaVersion.startsWith("3.") then "2.13" else m.scalaVersion
                )
              )
            case m: ScalaJsModule =>
              Seq(
                Dependency.make(
                  s"org.scala-lang::scala3-library::${scalaVersion}",
                  scalaVersion,
                  ScalaVersion.jsBinary(m.scalaJsVersion).map("sjs" + _)
                ),
                Dependency.make(
                  s"org.scala-js::scalajs-library:${m.scalaJsVersion}",
                  if m.scalaVersion.startsWith("3.") then "2.13" else m.scalaVersion
                )
              )
            case m: ScalaNativeModule =>
              val scalaSpecificVersion = s"${scalaVersion}+${m.scalaNativeVersion}"
              Seq(
                Dependency.make(s"org.scala-lang::scala3-library:${scalaVersion}", scalaVersion),
                Dependency.make(
                  s"org.scala-native::scala3lib::${scalaSpecificVersion}",
                  scalaVersion,
                  ScalaVersion.nativeBinary(m.scalaNativeVersion).map("native" + _)
                ),
                Dependency.make(
                  s"org.scala-native::scalalib::${scalaSpecificVersion}",
                  scalaVersion,
                  ScalaVersion.nativeBinary(m.scalaNativeVersion).map("native" + _)
                ),
                Dependency.make(
                  s"org.scala-native::javalib::${m.scalaNativeVersion}",
                  scalaVersion,
                  ScalaVersion.nativeBinary(m.scalaNativeVersion).map("native" + _)
                ),
                Dependency.make(
                  s"org.scala-native::nativelib::${m.scalaNativeVersion}",
                  scalaVersion,
                  ScalaVersion.nativeBinary(m.scalaNativeVersion).map("native" + _)
                ),
                Dependency.make(
                  s"org.scala-native::auxlib::${m.scalaNativeVersion}",
                  scalaVersion,
                  ScalaVersion.nativeBinary(m.scalaNativeVersion).map("native" + _)
                ),
                Dependency.make(
                  s"org.scala-native::clib::${m.scalaNativeVersion}",
                  scalaVersion,
                  ScalaVersion.nativeBinary(m.scalaNativeVersion).map("native" + _)
                ),
                Dependency.make(
                  s"org.scala-native::posixlib::${m.scalaNativeVersion}",
                  scalaVersion,
                  ScalaVersion.nativeBinary(m.scalaNativeVersion).map("native" + _)
                )
              )
            case m: ScalaModule => Seq(Dependency.make(s"org.scala-lang::scala3-library:${scalaVersion}", scalaVersion))
            case _              => Seq.empty
          }
        else
          ctx.module match {
            case m: ScalaJsTestModule =>
              Seq(
                Dependency.make(
                  s"org.scala-lang:scala-library:${scalaVersion}",
                  scalaVersion,
                  ScalaVersion.jsBinary(m.scalaJsVersion).map("sjs" + _)
                ),
                Dependency.make(
                  s"org.scala-js::scalajs-library:${m.scalaJsVersion}",
                  if m.scalaVersion.startsWith("3.") then "2.13" else m.scalaVersion
                ),
                Dependency.make(
                  s"org.scala-js::scalajs-test-bridge:${m.scalaJsVersion}",
                  if m.scalaVersion.startsWith("3.") then "2.13" else m.scalaVersion
                )
              )
            case m: ScalaJsModule =>
              Seq(
                Dependency.make(
                  s"org.scala-lang:scala-library:${scalaVersion}",
                  scalaVersion,
                  ScalaVersion.jsBinary(m.scalaJsVersion).map("sjs" + _)
                ),
                Dependency.make(
                  s"org.scala-js::scalajs-library:${m.scalaJsVersion}",
                  if m.scalaVersion.startsWith("3.") then "2.13" else m.scalaVersion
                )
              )
            case m: ScalaNativeModule =>
              val scalaSpecificVersion = s"${scalaVersion}+${m.scalaNativeVersion}"
              Seq(
                Dependency.make(s"org.scala-lang:scala-library:${scalaVersion}", scalaVersion),
                Dependency.make(
                  s"org.scala-native::scalalib::${scalaSpecificVersion}",
                  scalaVersion,
                  ScalaVersion.nativeBinary(m.scalaNativeVersion).map("native" + _)
                ),
                Dependency.make(
                  s"org.scala-native::javalib::${m.scalaNativeVersion}",
                  scalaVersion,
                  ScalaVersion.nativeBinary(m.scalaNativeVersion).map("native" + _)
                ),
                Dependency.make(
                  s"org.scala-native::nativelib::${m.scalaNativeVersion}",
                  scalaVersion,
                  ScalaVersion.nativeBinary(m.scalaNativeVersion).map("native" + _)
                ),
                Dependency.make(
                  s"org.scala-native::auxlib::${m.scalaNativeVersion}",
                  scalaVersion,
                  ScalaVersion.nativeBinary(m.scalaNativeVersion).map("native" + _)
                ),
                Dependency.make(
                  s"org.scala-native::clib::${m.scalaNativeVersion}",
                  scalaVersion,
                  ScalaVersion.nativeBinary(m.scalaNativeVersion).map("native" + _)
                ),
                Dependency.make(
                  s"org.scala-native::posixlib::${m.scalaNativeVersion}",
                  scalaVersion,
                  ScalaVersion.nativeBinary(m.scalaNativeVersion).map("native" + _)
                )
              )
            case m: ScalaModule => Seq(Dependency.make(s"org.scala-lang:scala-library:${scalaVersion}", scalaVersion))
            case _              => Seq.empty
          }
      scalaLibDeps
    }

  val classesTask = TaskBuilder
    .make[os.Path](
      name = "classes"
    )
    .build { ctx => ctx.out }

  val semanticdbDirTask = TaskBuilder
    .make[os.Path](
      name = "semanticdb"
    )
    .build { ctx => ctx.out }

  // this is localRunClasspath in mill ??
  val allClassesDirsTask = CachedTaskBuilder
    .make[Seq[os.Path]](
      name = "allClassesDirs",
      transitive = true
    )
    .dependsOn(classesTask)
    .build { ctx =>
      Seq(ctx.depResults._1) ++ ctx.transitiveResults.flatten.flatten.reverse.distinct.reverse
    }

  val compileClasspathTask = CachedTaskBuilder
    .make[Seq[os.Path]](
      name = "compileClasspath",
      transitive = true
    )
    .dependsOn(scalaVersionTask)
    .dependsOn(mandatoryDependenciesTask)
    .dependsOn(allDependenciesTask)
    .dependsOn(allClassesDirsTask)
    .build { ctx =>
      // we feed even this module's classes dir because of javac annotation processing,
      // it can generate java sources.. and then scala sources can depend on them
      val (scalaVersion, mandatoryDependencies, dependencies, allClassesDirs) = ctx.depResults
      val depsJars = DependencyResolver
        .fetchFiles(mandatoryDependencies ++ dependencies, Some(ctx.notifications))
      (allClassesDirs ++ depsJars).reverse.distinct.reverse
    }

  val javaSemanticdbVersionTask = ConfigValueTask[String](
    name = "javaSemanticdbVersion",
    execute = { ctx =>
      ctx.module match {
        case m: JavaModule => m.javaSemanticdbVersion
        case _             => "0.11.1"
      }
    }
  )

  val scalaSemanticdbVersionTask = CachedTaskBuilder
    .make[String](
      name = "scalaSemanticdbVersion"
    )
    .dependsOn(scalaVersionTask)
    .build { ctx =>
      val scalaVersion = ctx.depResults._1
      ctx.module match {
        case m: ScalaModule =>
          Option(m.scalaSemanticdbVersion).getOrElse {
            scalaVersion match {
              case s"2.13.${minor}" =>
                val minorNum = minor.toInt
                if minorNum == 1 then "4.6.0"
                else if minorNum < 8 then "4.8.4"
                else if minorNum == 8 then "4.8.9"
                else if minorNum == 9 then "4.9.0"
                else if minorNum == 10 then "4.9.3"
                else if minorNum == 11 then "4.9.9"
                else if minorNum == 12 then "4.12.3"
                else if minorNum == 13 then "4.13.9"
                else if minorNum == 14 then "4.14.1"
                else "4.14.5"
              case _ => "4.14.5"
            }
          }
        case _ => "4.14.5"
      }
    }

  val javacAnnotationProcessorDepsTask = ConfigValueTask[Seq[String]](
    name = "javacAnnotationProcessorDeps",
    execute = { ctx =>
      ctx.module match {
        case m: JavaModule => m.javacAnnotationProcessorDeps.asScala.toSeq
        case _             => Seq.empty
      }
    }
  )

  val javacAnnotationProcessorsTask = CachedTaskBuilder
    .make[Seq[os.Path]](
      name = "javacAnnotationProcessors"
    )
    .dependsOn(scalaVersionTask)
    .dependsOn(javacAnnotationProcessorDepsTask)
    .build { ctx =>
      val (scalaVersion, javacAnnotationProcessorDeps) = ctx.depResults
      val processorJars = DependencyResolver.fetchFiles(
        javacAnnotationProcessorDeps.map(d => Dependency.make(d, scalaVersion)),
        Some(ctx.notifications)
      )
      processorJars
    }

  val scalacPluginDepsTask = ConfigValueTask[Seq[String]](
    name = "scalacPluginDeps",
    execute = { ctx =>
      ctx.module match {
        case m: ScalaModule => m.scalacPluginDeps.asScala.toSeq
        case _              => Seq.empty
      }
    }
  )

  val scalacPluginsTask = CachedTaskBuilder
    .make[Seq[os.Path]](
      name = "scalacPlugins"
    )
    .dependsOn(scalaVersionTask)
    .dependsOn(scalacPluginDepsTask)
    .build { ctx =>
      val (scalaVersion, scalacPluginDeps) = ctx.depResults
      val scalaPlatformDeps =
        if scalaVersion.startsWith("3.") then
          ctx.module match {
            case m: ScalaNativeModule => Seq(s"org.scala-native:::nscplugin:${m.scalaNativeVersion}")
            case _                    => Seq.empty
          }
        else
          ctx.module match {
            case m: ScalaJsModule     => Seq(s"org.scala-js:::scalajs-compiler:${m.scalaJsVersion}")
            case m: ScalaNativeModule => Seq(s"org.scala-native:::nscplugin:${m.scalaNativeVersion}")
            case _                    => Seq.empty
          }
      val allDeps = scalacPluginDeps ++ scalaPlatformDeps
      val pluginJars = DependencyResolver.fetchFiles(
        allDeps.map(d => Dependency.make(d, scalaVersion)), // .exclude(dependency.Module("*", "*"))),
        Some(ctx.notifications)
      )
      pluginJars
    }

  val compilerDepsTask = CachedTaskBuilder
    .make[Seq[Dependency]](
      name = "compilerDeps"
    )
    .dependsOn(scalaVersionTask)
    .build { ctx =>
      val scalaVersion = ctx.depResults._1
      // TODO scalajs compiler on scala2?
      val compilerDeps =
        if scalaVersion.startsWith("3.") then
          ctx.module match {
            case m: ScalaJsModule =>
              Seq(
                Dependency.make(s"org.scala-lang::scala3-compiler:${scalaVersion}", scalaVersion)
              )
            case _ =>
              Seq(Dependency.make(s"org.scala-lang::scala3-compiler:${scalaVersion}", scalaVersion))
          }
        else
          ctx.module match {
            case _ =>
              Seq(
                Dependency.make(s"org.scala-lang:scala-compiler:${scalaVersion}", scalaVersion),
                Dependency.make(s"org.scala-lang:scala-reflect:${scalaVersion}", scalaVersion)
              )
          }
      compilerDeps
    }

  // returns classes dir
  val compileTask = TaskBuilder
    .make[DederPath](
      name = "compile",
      transitive = true
    )
    .dependsOn(sourcesTask)
    .dependsOn(generatedSourcesTask)
    .dependsOn(javaHomeTask)
    .dependsOn(javaVersionTask)
    .dependsOn(javacOptionsTask)
    .dependsOn(scalacOptionsTask)
    .dependsOn(scalaVersionTask)
    .dependsOn(compilerDepsTask)
    .dependsOn(compileClasspathTask)
    .dependsOn(classesTask)
    .dependsOn(scalacPluginsTask)
    .dependsOn(javacAnnotationProcessorsTask)
    .build { ctx =>
      val (
        sourceDirs,
        generatedSourcesDir,
        javaHome,
        javaVersion,
        javacOptions,
        scalacOptions,
        scalaVersion,
        compilerDeps,
        compileClasspath,
        classesDir,
        scalacPlugins,
        javacAnnotationProcessors
      ) = ctx.depResults

      JdkUtils.checkCompat(JdkUtils.getVersion(scala.util.Properties.javaSpecVersion), scalaVersion)

      val sourceFiles = sourceDirs
        .map(_.absPath)
        .flatMap { sourceDir =>
          if os.exists(sourceDir) then
            os.walk(
              sourceDir,
              skip = p => {
                if os.isDir(p) then false
                else if os.isFile(p) then !(p.ext == "scala" || p.ext == "java")
                else true
              }
            )
          else Seq.empty
        }
        .filter(os.isFile)

      // annotation processors need generated sources dir to exist
      os.makeDir.all(generatedSourcesDir)

      val compilerJars = DependencyResolver.fetchFiles(compilerDeps)

      val zincCacheFile = ctx.out / "inc_compile.zip"
      val zincLogger = new DederZincLogger(ctx.notifications, ctx.module.id)

      val finalJavacOptions = javacOptions ++
        Option
          .when(javacAnnotationProcessors.nonEmpty)(
            Seq(
              "-s",
              generatedSourcesDir.toString,
              "-processorpath",
              javacAnnotationProcessors.map(_.toString).mkString(File.pathSeparator)
            )
          )
          .toSeq
          .flatten ++
        javaVersion.map(v => Seq("--release", v)).getOrElse(Seq.empty)

      val platformSpecificScalacOptions = ctx.module match {
        case module: ScalaJsModule => if scalaVersion.startsWith("3.") then Seq("-scalajs") else Seq.empty
        case _                     => Seq.empty
      }
      val finalScalacOptions =
        scalacOptions ++ scalacPlugins.map(p => s"-Xplugin:${p.toString}") ++ platformSpecificScalacOptions

      ZincCompilersCache
        .get(scalaVersion)
        .compile(
          javaHome = javaHome.map(_.toNIO),
          scalaVersion = scalaVersion,
          compilerJars = compilerJars,
          compileClasspath = compileClasspath,
          zincCacheFile = zincCacheFile,
          sources = sourceFiles,
          classesDir = classesDir,
          scalacOptions = finalScalacOptions,
          javacOptions = finalJavacOptions,
          zincLogger = zincLogger,
          moduleId = ctx.module.id,
          notifications = ctx.notifications
        )
      DederPath(classesDir)
    }

  // BSP compile: same as compileTask but always generates SemanticDB for IDE features (go-to-def, scalafix, etc.)
  val compileBspTask = TaskBuilder
    .make[DederPath](
      name = "compileBsp",
      transitive = true
    )
    .dependsOn(sourcesTask)
    .dependsOn(generatedSourcesTask)
    .dependsOn(javaHomeTask)
    .dependsOn(javaVersionTask)
    .dependsOn(javacOptionsTask)
    .dependsOn(scalacOptionsTask)
    .dependsOn(scalaVersionTask)
    .dependsOn(compilerDepsTask)
    .dependsOn(compileClasspathTask)
    .dependsOn(classesTask)
    .dependsOn(semanticdbDirTask)
    .dependsOn(scalacPluginsTask)
    .dependsOn(javacAnnotationProcessorsTask)
    .dependsOn(javaSemanticdbVersionTask)
    .dependsOn(scalaSemanticdbVersionTask)
    .build { ctx =>
      val (
        sourceDirs,
        generatedSourcesDir,
        javaHome,
        javaVersion,
        javacOptions,
        scalacOptions,
        scalaVersion,
        compilerDeps,
        compileClasspath,
        classesDir,
        semanticdbDir,
        scalacPlugins,
        javacAnnotationProcessors,
        javaSemanticdbVersion,
        scalaSemanticdbVersion
      ) = ctx.depResults

      JdkUtils.checkCompat(JdkUtils.getVersion(scala.util.Properties.javaSpecVersion), scalaVersion)

      val sourceFiles = sourceDirs
        .map(_.absPath)
        .flatMap { sourceDir =>
          if os.exists(sourceDir) then
            os.walk(
              sourceDir,
              skip = p => {
                if os.isDir(p) then false
                else if os.isFile(p) then !(p.ext == "scala" || p.ext == "java")
                else true
              }
            )
          else Seq.empty
        }
        .filter(os.isFile)

      // annotation processors need generated sources dir to exist
      os.makeDir.all(generatedSourcesDir)

      val compilerJars = DependencyResolver.fetchFiles(compilerDeps)

      val zincCacheFile = ctx.out / "inc_compile.zip"
      val zincLogger = new DederZincLogger(ctx.notifications, ctx.module.id)

      // TODO maybe check if there are any .java files first ?
      val semanticdbJavacJar = DependencyResolver.fetchFiles(
        Seq(Dependency.make(s"com.sourcegraph:semanticdb-javac:${javaSemanticdbVersion}", scalaVersion))
      )
      val allJavacAnnotationProcessors = javacAnnotationProcessors ++ semanticdbJavacJar

      val finalJavacOptions = javacOptions ++
        Option
          .when(allJavacAnnotationProcessors.nonEmpty)(
            Seq(
              "-s",
              generatedSourcesDir.toString,
              "-processorpath",
              allJavacAnnotationProcessors.map(_.toString).mkString(File.pathSeparator)
            )
          )
          .toSeq
          .flatten ++
        javaVersion.map(v => Seq("--release", v)).getOrElse(Seq.empty) ++
        // https://github.com/sourcegraph/scip-java/issues/390
        Some(s"-Xplugin:semanticdb -sourceroot:${DederGlobals.projectRootDir} -targetroot:${semanticdbDir} -build-tool:sbt")

      // For Scala 2: add semanticdb-scalac plugin
      val semanticdbScalacJar =
        if scalaVersion.startsWith("3.") then Seq.empty
        else
          DependencyResolver.fetchFiles(
            Seq(Dependency.make(s"org.scalameta:::semanticdb-scalac:${scalaSemanticdbVersion}", scalaVersion))
          )
      val allScalacPlugins = scalacPlugins ++ semanticdbScalacJar

      val semanticDbScalacOpts =
        if scalaVersion.startsWith("3.") then
          Seq(
            "-Xsemanticdb",
            "-sourceroot",
            DederGlobals.projectRootDir.toString,
            "-semanticdb-target",
            semanticdbDir.toString
          )
        else
          Seq(
            "-Yrangepos",
            s"-P:semanticdb:sourceroot:${DederGlobals.projectRootDir}",
            s"-P:semanticdb:targetroot:${semanticdbDir}"
          )
      val platformSpecificScalacOptions = ctx.module match {
        case module: ScalaJsModule => if scalaVersion.startsWith("3.") then Seq("-scalajs") else Seq.empty
        case _                     => Seq.empty
      }
      val finalScalacOptions =
        scalacOptions ++ allScalacPlugins
          .map(p => s"-Xplugin:${p.toString}") ++ platformSpecificScalacOptions ++ semanticDbScalacOpts

      ZincCompilersCache
        .get(scalaVersion)
        .compile(
          javaHome = javaHome.map(_.toNIO),
          scalaVersion = scalaVersion,
          compilerJars = compilerJars,
          compileClasspath = compileClasspath,
          zincCacheFile = zincCacheFile,
          sources = sourceFiles,
          classesDir = classesDir,
          scalacOptions = finalScalacOptions,
          javacOptions = finalJavacOptions,
          zincLogger = zincLogger,
          moduleId = ctx.module.id,
          notifications = ctx.notifications
        )
      DederPath(classesDir)
    }

  val jvmOptionsTask = ConfigValueTask[Seq[String]](
    name = "jvmOptions",
    execute = { ctx =>
      ctx.module match {
        case m: JavaModule => m.jvmOptions.asScala.toSeq
        case _             => Seq.empty
      }
    }
  )

  val runClasspathTask = CachedTaskBuilder
    .make[Seq[os.Path]](
      name = "runClasspath",
      transitive = true
    )
    .dependsOn(compileTask)
    .dependsOn(compileClasspathTask)
    .dependsOn(resourcesTask)
    .build { ctx =>
      val (_, compileClasspath, resourceDirs) = ctx.depResults
      val resources = resourceDirs.map(_.absPath)
      compileClasspath ++ resources
    }

  val mainClassesTask = CachedTaskBuilder
    .make[Seq[String]](
      name = "mainClasses"
    )
    .dependsOn(compileTask)
    .dependsOn(classesTask)
    .build { ctx =>
      val (_, classesDir) = ctx.depResults
      MainClassesDiscovery.discover(Seq(classesDir))
    }

  val mainClassTask = ConfigValueTask[Option[String]](
    name = "mainClass",
    execute = { ctx =>
      ctx.module match {
        case m: JavaModule => Option(m.mainClass)
        case _             => None
      }
    }
  )

  val finalMainClassTask = CachedTaskBuilder
    .make[Option[String]](
      name = "finalMainClass"
    )
    .dependsOn(mainClassTask)
    .dependsOn(mainClassesTask)
    .build { ctx =>
      val (mainClass, discoveredMainClasses) = ctx.depResults
      mainClass
        .orElse {
          Option.when(discoveredMainClasses.length == 1)(discoveredMainClasses.head)
        }
    }

  case class ManifestEntries(
      mainAttributes: Map[String, String],
      groups: Map[String, Map[String, String]]
  ) derives JsonRW {
    def toJarManifest: JarManifest = {
      val base = JarManifest.Default.add(mainAttributes.toSeq*)
      groups.foldLeft(base) { case (m, (group, attrs)) =>
        m.addGroup(group, attrs.toSeq*)
      }
    }
  }

  object ManifestEntries {
    val Empty: ManifestEntries = ManifestEntries(Map.empty, Map.empty)

    given Hashable[ManifestEntries] with {
      override def hashStr(value: ManifestEntries): String =
        Seq(value.mainAttributes.hashStr, value.groups.hashStr).hashStr
    }
  }

  val manifestSettingsTask = ConfigValueTask[ManifestEntries](
    name = "manifest",
    execute = { ctx =>
      ctx.module match {
        case m: JavaModule =>
          ManifestEntries(
            mainAttributes = m.manifest.mainAttributes.asScala.toMap,
            groups = m.manifest.groups.asScala.view.mapValues(_.asScala.toMap).toMap
          )
        case _ => ManifestEntries.Empty
      }
    }
  )

  val pomSettingsTask = ConfigValueTask[Option[PomSettings]](
    name = "pomSettings",
    execute = { ctx =>
      ctx.module match {
        case jm: JavaModule =>
          val pom = jm.pomSettings
          if jm.publish then {
            if pom == null then throw RuntimeException(s"POM settings are not set for ${jm.id}")
            val finalArtifactId = jm match {
              case m: ScalaJsModule =>
                s"${pom.artifactId}_sjs${ScalaVersion.jsBinary(m.scalaJsVersion).get}_${ScalaVersion.binary(m.scalaVersion)}"
              case m: ScalaNativeModule =>
                s"${pom.artifactId}_native${ScalaVersion.nativeBinary(m.scalaNativeVersion).get}_${ScalaVersion.binary(m.scalaVersion)}"
              case m: ScalaModule =>
                s"${pom.artifactId}_${ScalaVersion.binary(m.scalaVersion)}"
              case _ =>
                pom.artifactId
            }
            val resolvedVersion =
              if pom.version != null then pom.version
              else GitSemVer.detectVersion(DederGlobals.projectRootDir)
            Some(
              PomSettings(
                groupId = pom.groupId,
                artifactId = finalArtifactId,
                version = resolvedVersion
              )
            )
          } else {
            ctx.notifications.add(
              ServerNotification.logDebug(
                s"Skipping POM generation for module ${jm.id} because publish is set to false"
              )
            )
            None
          }
        case other => throw RuntimeException(s"POM settings cannot be applied to $other")
      }
    }
  )

  val finalManifestSettingsTask = CachedTaskBuilder
    .make[ManifestEntries](name = "finalManifest")
    .dependsOn(manifestSettingsTask)
    .dependsOn(finalMainClassTask)
    .dependsOn(pomSettingsTask)
    .build { ctx =>
      val (manifestEntries, mainClass, pomSettings) = ctx.depResults
      import java.util.jar.Attributes.Name as JarName

      // defaults from pom settings (when available)
      val pomDefaults = pomSettings match {
        case Some(pom) =>
          Map(
            JarName.IMPLEMENTATION_TITLE.toString -> pom.artifactId,
            JarName.IMPLEMENTATION_VERSION.toString -> pom.version,
            JarName.IMPLEMENTATION_VENDOR.toString -> pom.groupId,
            JarName.SPECIFICATION_TITLE.toString -> pom.artifactId,
            JarName.SPECIFICATION_VERSION.toString -> pom.version,
            JarName.SPECIFICATION_VENDOR.toString -> pom.groupId
          )
        case None =>
          Map(
            JarName.IMPLEMENTATION_TITLE.toString -> ctx.module.id
          )
      }

      // main class entry (when available)
      val mainClassEntry = mainClass.map(mc => JarName.MAIN_CLASS.toString -> mc)

      // precedence: pomDefaults < mainClass < user manifest entries
      val merged = pomDefaults ++ mainClassEntry ++ manifestEntries.mainAttributes
      manifestEntries.copy(mainAttributes = merged)
    }

  val runTask = TaskBuilder
    .make[Seq[String]](
      name = "run",
      singleton = true
    )
    .dependsOn(runClasspathTask)
    .dependsOn(mainClassesTask)
    .dependsOn(finalMainClassTask)
    .dependsOn(jvmOptionsTask)
    .build { ctx =>
      val (runClasspath, discoveredMainClasses, finalMainClass, jvmOptions) = ctx.depResults
      finalMainClass match {
        case Some(mc) =>
          val cp = runClasspath.map(_.toString)
          val cmd = Seq("java") ++ jvmOptions ++ Seq("-cp", cp.mkString(File.pathSeparator), mc) ++ ctx.args
          logger.debug(s"Client should run command: ${cmd}")
          val forkEnv = ctx.module match {
            case m: JavaModule => m.forkEnv.asScala.to(Map)
            case _             => Map.empty
          }
          ctx.notifications.add(ServerNotification.RunSubprocess(cmd, forkEnv, ctx.watch))
          cmd
        case None =>
          if discoveredMainClasses.length > 1 then
            throw new Exception(
              s"Multiple main classes discovered for module '${ctx.module.id}': ${discoveredMainClasses.mkString(", ")}. " +
                "Please specify which one to run in deder.pkl or use runMain task with main class argument."
            )
          else throw new Exception(s"No main class specified for module: ${ctx.module.id}")
      }
    }

  val runMainTask = TaskBuilder
    .make[Seq[String]](
      name = "runMain",
      singleton = true
    )
    .dependsOn(runClasspathTask)
    .dependsOn(mainClassesTask)
    .dependsOn(jvmOptionsTask)
    .build { ctx =>
      val (runClasspath, discoveredMainClasses, jvmOptions) = ctx.depResults
      val selectedMainClass = ctx.args.headOption.getOrElse(
        throw RuntimeException(
          "No main class specified to run. Please provide the main class as an argument. " +
            s"Possible candidates: ${discoveredMainClasses.mkString(", ")}"
        )
      )
      val finalMainClass = discoveredMainClasses.find(_ == selectedMainClass)
      finalMainClass match {
        case Some(mc) =>
          val cp = runClasspath.map(_.toString)
          val cmd = Seq("java") ++ jvmOptions ++ Seq("-cp", cp.mkString(File.pathSeparator), mc) ++ ctx.args.tail
          logger.debug(s"Client should run command: ${cmd}")
          val forkEnv = ctx.module match {
            case m: JavaModule => m.forkEnv.asScala.to(Map)
            case _             => Map.empty
          }
          ctx.notifications.add(ServerNotification.RunSubprocess(cmd, forkEnv, ctx.watch))
          cmd
        case None =>
          throw new RuntimeException(
            s"Class '${selectedMainClass}' with main method not found for module '${ctx.module.id}'. " +
              s"Possible candidates: ${discoveredMainClasses.mkString(", ")}"
          )
      }
    }

  val runMvnAppTask = TaskBuilder
    .make[Seq[String]](
      name = "runMvnApp"
    )
    .dependsOn(sourcesTask)
    .dependsOn(scalaVersionTask)
    .dependsOn(jvmOptionsTask)
    .build { ctx =>
      val (sources, scalaVersion, jvmOptions) = ctx.depResults
      val sourcePaths = sources.map(_.absPath).filter(os.exists(_)).map(_.toString)

      val userMvnAppsMap: Map[String, DederProject.MvnApp] = ctx.module match {
        case m: JavaModule => m.mvnApps.asScala.toMap
        case _             => Map.empty
      }
      val autoMvnAppsMap: Map[String, DederProject.MvnApp] = ctx.module match {
        case m: ScalaModule =>
          val scalafmtDep = "org.scalameta:scalafmt-cli_2.13:3.10.7"
          val scalafmtMain = "org.scalafmt.cli.Cli"
          Map(
            "fmt" -> DederProject.MvnApp(scalafmtDep, scalafmtMain, sourcePaths.asJava),
            "fmtCheck" -> DederProject.MvnApp(scalafmtDep, scalafmtMain, (Seq("--check") ++ sourcePaths).asJava)
          )
        case _ => Map.empty
      }
      val effectiveMap = (userMvnAppsMap ++ autoMvnAppsMap).map { case (name, tc) =>
        name -> (tc.dep, tc.mainClass, tc.args.asScala.toSeq)
      }

      val mvnAppName = ctx.args.headOption.getOrElse(
        throw new RuntimeException(
          s"No maven app name specified. Available maven apps: ${effectiveMap.keys.mkString(", ")}"
        )
      )
      effectiveMap.get(mvnAppName) match {
        case Some((dep, mainClass, args)) =>
          val dependency = Dependency.make(dep, scalaVersion)
          val jars = DependencyResolver.fetchFiles(Seq(dependency), Some(ctx.notifications))
          val cp = jars.map(_.toString).mkString(File.pathSeparator)
          val commandArgs = args ++ ctx.args.tail
          val cmd = Seq("java") ++ jvmOptions ++ Seq("-cp", cp, mainClass) ++ commandArgs
          logger.info(s"Running maven app '${mvnAppName}': ${cmd}")
          val forkEnv = ctx.module match {
            case m: JavaModule => m.forkEnv.asScala.to(Map)
            case _             => Map.empty
          }
          ctx.notifications.add(ServerNotification.RunSubprocess(cmd, forkEnv, false))
          cmd
        case _ =>
          throw new RuntimeException(
            s"Maven app '${mvnAppName}' not found for module '${ctx.module.id}'. " +
              s"Available maven apps: ${effectiveMap.keys.mkString(", ")}"
          )
      }
    }

  val fixTask = TaskBuilder
    .make[Seq[String]](
      name = "fix",
      supportedModuleTypes = Set(
        ModuleType.SCALA,
        ModuleType.SCALA_TEST,
        ModuleType.SCALA_JS,
        ModuleType.SCALA_JS_TEST,
        ModuleType.SCALA_NATIVE,
        ModuleType.SCALA_NATIVE_TEST
      )
    )
    .dependsOn(sourcesTask)
    .dependsOn(scalaVersionTask)
    .dependsOn(scalacOptionsTask)
    .dependsOn(jvmOptionsTask)
    .dependsOn(compileBspTask)
    .dependsOn(compileClasspathTask)
    .dependsOn(semanticdbDirTask)
    .build { ctx =>
      val (sources, scalaVersion, scalacOptions, jvmOptions, _, compileClasspath, semanticdbDir) = ctx.depResults
      val dependency = Dependency.make(ScalafixUtils.scalafixDep(scalaVersion), scalaVersion)
      val jars = DependencyResolver.fetchFiles(Seq(dependency), Some(ctx.notifications))
      val cp = jars.map(_.toString).mkString(File.pathSeparator)
      val sourcePaths = sources.map(_.absPath).filter(os.exists(_)).map(_.toString)
      val scalafixArgs =
        ScalafixUtils.buildArgs(scalaVersion, scalacOptions, compileClasspath, semanticdbDir, sourcePaths, ctx.args)
      val cmd = Seq("java") ++ jvmOptions ++ Seq("-cp", cp, "scalafix.cli.Cli") ++ scalafixArgs
      logger.info(s"Running scalafix fix: ${cmd}")
      val forkEnv = ctx.module match {
        case m: JavaModule => m.forkEnv.asScala.to(Map)
        case _             => Map.empty
      }
      ctx.notifications.add(ServerNotification.RunSubprocess(cmd, forkEnv, ctx.watch))
      cmd
    }

  val fixCheckTask = TaskBuilder
    .make[Seq[String]](
      name = "fixCheck",
      supportedModuleTypes = Set(
        ModuleType.SCALA,
        ModuleType.SCALA_TEST,
        ModuleType.SCALA_JS,
        ModuleType.SCALA_JS_TEST,
        ModuleType.SCALA_NATIVE,
        ModuleType.SCALA_NATIVE_TEST
      )
    )
    .dependsOn(sourcesTask)
    .dependsOn(scalaVersionTask)
    .dependsOn(scalacOptionsTask)
    .dependsOn(jvmOptionsTask)
    .dependsOn(compileBspTask)
    .dependsOn(compileClasspathTask)
    .dependsOn(semanticdbDirTask)
    .build { ctx =>
      val (sources, scalaVersion, scalacOptions, jvmOptions, _, compileClasspath, semanticdbDir) = ctx.depResults
      val dependency = Dependency.make(ScalafixUtils.scalafixDep(scalaVersion), scalaVersion)
      val jars = DependencyResolver.fetchFiles(Seq(dependency), Some(ctx.notifications))
      val cp = jars.map(_.toString).mkString(File.pathSeparator)
      val sourcePaths = sources.map(_.absPath).filter(os.exists(_)).map(_.toString)
      val scalafixArgs = ScalafixUtils.buildArgs(
        scalaVersion,
        scalacOptions,
        compileClasspath,
        semanticdbDir,
        sourcePaths,
        Seq("--test") ++ ctx.args
      )
      val cmd = Seq("java") ++ jvmOptions ++ Seq("-cp", cp, "scalafix.cli.Cli") ++ scalafixArgs
      logger.info(s"Running scalafix fixCheck: ${cmd}")
      val forkEnv = ctx.module match {
        case m: JavaModule => m.forkEnv.asScala.to(Map)
        case _             => Map.empty
      }
      ctx.notifications.add(ServerNotification.RunSubprocess(cmd, forkEnv, false))
      cmd
    }

  val testClassesTask = CachedTaskBuilder
    .make[Seq[DiscoveredFrameworkTests]](
      name = "testClasses",
      supportedModuleTypes = Set(
        ModuleType.JAVA_TEST,
        ModuleType.SCALA_TEST,
        ModuleType.SCALA_JS_TEST,
        ModuleType.SCALA_NATIVE_TEST
      )
    )
    .dependsOn(classesTask)
    .dependsOn(runClasspathTask)
    .build { ctx =>
      val (classesDir, runClasspath) = ctx.depResults
      val runtimeClasspath = (Seq(classesDir) ++ runClasspath).reverse.distinct.reverse
      ClassLoaderUtils.withTestsClassLoader(runtimeClasspath) { classLoader =>
        val frameworkClassNames = ctx.module match {
          case m: JavaTestModule        => m.testFrameworks.asScala.toSeq
          case m: ScalaTestModule       => m.testFrameworks.asScala.toSeq
          case m: ScalaJsTestModule     => m.testFrameworks.asScala.toSeq
          case m: ScalaNativeTestModule => m.testFrameworks.asScala.toSeq
          case _                        => Seq.empty
        }
        val testDiscovery = DederTestDiscovery(
          classLoader = classLoader,
          testClassesDir = classesDir,
          testClasspath = runtimeClasspath,
          frameworkClassNames = frameworkClassNames,
          logger = DederTestLogger(ctx.notifications, ctx.module.id)
        )
        testDiscovery.discover()
      }
    }

  val testTask = TaskBuilder
    .make[DederTestResults](
      name = "test",
      supportedModuleTypes = Set(ModuleType.JAVA_TEST, ModuleType.SCALA_TEST)
    )
    .dependsOn(runClasspathTask)
    .dependsOn(jvmOptionsTask)
    .dependsOn(javaHomeTask)
    .dependsOn(testClassesTask)
    .buildWithSummary(
      execute = { ctx =>
        val (runClasspath, jvmOptions, javaHome, discoveredTests) = ctx.depResults
        OutputCaptureContext.withCapture(ctx.notifications, ctx.module.id) {
          val (fork, forkEnv) = ctx.module match {
            case m: JavaTestModule  => (m.fork, m.forkEnv.asScala.to(Map))
            case m: ScalaTestModule => (m.fork, m.forkEnv.asScala.to(Map))
            case _                  => (true, Map.empty)
          }
          val testOptions = DederTestOptions(ctx.args)
          if fork then {
            ForkedTestOrchestrator.run(
              discoveredTests = discoveredTests,
              runtimeClasspath = runClasspath,
              jvmOptions = jvmOptions,
              envVars = forkEnv,
              javaHome = javaHome.map(_.toString),
              testOptions = testOptions,
              notifications = ctx.notifications,
              moduleId = ctx.module.id,
              outDir = ctx.out,
              workerThreads = DederGlobals.testWorkerThreads
            )
          } else
            ClassLoaderUtils.withTestsClassLoader(runClasspath) { classLoader =>
              val logger = DederTestLogger(ctx.notifications, ctx.module.id)
              Using.resource(java.util.concurrent.Executors.newFixedThreadPool(DederGlobals.testWorkerThreads)) {
                executorService =>
                  val testRunner = DederTestRunner(executorService, discoveredTests, Map.empty, classLoader, logger)
                  testRunner.run(testOptions)
              }
            }
        }
      },
      isResultSuccessful = _.success,
      summarize = DederTestResults.summarize
    )

  val jarTask = CachedTaskBuilder
    .make[os.Path](name = "jar")
    .dependsOn(compileTask)
    .dependsOn(finalManifestSettingsTask)
    .build { ctx =>
      val (localClasspath, manifestEntries) = ctx.depResults
      val resultJarPath = ctx.out / s"${ctx.module.id}.jar"
      val jarInputPaths = Seq(localClasspath.absPath)
      JarUtils.createJar(
        resultJarPath,
        jarInputPaths,
        manifestEntries.toJarManifest
      )
      resultJarPath
    }

  val allJarsTask = CachedTaskBuilder
    .make[Seq[os.Path]](
      name = "allJars",
      transitive = true
    )
    .dependsOn(jarTask)
    .build { ctx =>
      val jar = ctx.depResults._1
      ctx.transitiveResults.flatten.flatten.prepended(jar).reverse.distinct.reverse
    }

  val assemblyTask = CachedTaskBuilder
    .make[os.Path](
      name = "assembly",
      supportedModuleTypes = Set(ModuleType.JAVA, ModuleType.JAVA_TEST, ModuleType.SCALA, ModuleType.SCALA_TEST)
    )
    .dependsOn(scalaVersionTask)
    .dependsOn(finalManifestSettingsTask)
    .dependsOn(mandatoryDependenciesTask)
    .dependsOn(allDependenciesTask)
    .dependsOn(allJarsTask)
    .build { ctx =>
      val (scalaVersion, manifestEntries, mandatoryDependencies, dependencies, allModulesJars) =
        ctx.depResults
      val depsJars = DependencyResolver.fetchFiles(mandatoryDependencies ++ dependencies, Some(ctx.notifications))
      val tmpDir = ctx.out / "jars"
      os.makeDir.all(tmpDir)
      allModulesJars.zipWithIndex.foreach { case (jar, index) =>
        val jarName = s"${index + 1}-${jar.last}"
        os.copy.over(jar, tmpDir / jarName)
      }
      val allJars = os.list(tmpDir) ++ depsJars
      val mergedJar = ctx.out / "mergedJar.jar"
      JarUtils.mergeJars(mergedJar, allJars, manifestEntries.toJarManifest)
      val resultJarPath = ctx.out / "out.jar"
      JarUtils.createAssemblyJar(resultJarPath, mergedJar)
      resultJarPath
    }

  val moduleDepsPomSettingsTask = CachedTaskBuilder
    .make[Seq[Seq[PomSettings]]](
      name = "moduleDepsPomSettings",
      transitive = true
    )
    .dependsOn(pomSettingsTask)
    .build { ctx =>
      val pom: Option[PomSettings] = ctx.depResults._1
      Seq(pom.toSeq) ++ ctx.transitiveResults.flatten.flatten
    }

  val sourcesJarTask = CachedTaskBuilder
    .make[Option[os.Path]](name = "sourcesJar")
    .dependsOn(pomSettingsTask)
    .dependsOn(sourcesTask)
    .build { ctx =>
      val (pomSettingsOpt, sources) = ctx.depResults
      pomSettingsOpt.map { pomSettings =>
        os.makeDir.all(ctx.out)
        val resultJarPath = ctx.out / s"${pomSettings.artifactId}-sources.jar"
        os.remove(resultJarPath)
        os.zip(resultJarPath, sources.map(_.absPath).filter(os.exists(_)))
        resultJarPath
      }
    }

  val javadocJarTask = CachedTaskBuilder
    .make[Option[os.Path]](name = "javadocJar")
    .dependsOn(scalaVersionTask)
    .dependsOn(pomSettingsTask)
    .dependsOn(sourcesTask)
    .dependsOn(compilerDepsTask)
    .dependsOn(compileClasspathTask)
    .dependsOn(compileTask)
    .dependsOn(classesTask)
    .build { ctx =>
      val (scalaVersion, pomSettingsOpt, sources, compilerDeps, compileClasspath, _, classesDir) = ctx.depResults
      pomSettingsOpt.map { pomSettings =>
        os.remove.all(ctx.out)
        os.makeDir.all(ctx.out)
        val generatedDir = ctx.out / "generated"
        os.makeDir.all(generatedDir)
        val sourceFiles = sources
          .map(_.absPath)
          .flatMap { sourceDir =>
            if os.exists(sourceDir) then
              os.walk(
                sourceDir,
                skip = p => {
                  if os.isDir(p) then false
                  else if os.isFile(p) then !(p.ext == "scala" || p.ext == "java")
                  else true
                }
              )
            else Seq.empty
          }
          .filter(os.isFile)
        ctx.module match {
          case module: ScalaModule =>
            if scalaVersion.startsWith("3.") then {
              val tastyFiles =
                if os.exists(classesDir) then
                  os.walk(
                    classesDir,
                    skip = p => {
                      if os.isDir(p) then false
                      else if os.isFile(p) then !(p.ext == "tasty")
                      else true
                    }
                  )
                else Seq.empty
              if tastyFiles.isEmpty then
                throw RuntimeException(s"No .tasty files found in ${classesDir} for generating scaladoc")
              val deps = Seq(Dependency.make(s"org.scala-lang::scaladoc:${scalaVersion}", scalaVersion))
              val depsJars = DependencyResolver.fetchFiles(deps, Some(ctx.notifications))
              ClassLoaderUtils.withClassLoader(depsJars, parent = null) { classLoader =>
                val scaladocClass = classLoader.loadClass("dotty.tools.scaladoc.Main")
                val scaladocMethod = scaladocClass.getMethod("run", classOf[Array[String]])
                val args = Array[String](
                  "-d",
                  generatedDir.toString,
                  "-classpath",
                  compileClasspath.mkString(File.pathSeparator),
                  "--"
                ) ++ tastyFiles.filter(os.isFile(_)).map(_.toString)
                val scaladocObj = scaladocClass.getConstructor().newInstance()
                scaladocMethod.invoke(scaladocObj, args)
              }
            } else {
              val depsJars = DependencyResolver.fetchFiles(compilerDeps, Some(ctx.notifications))
              ClassLoaderUtils.withClassLoader(depsJars, parent = null) { classLoader =>
                val scaladocClass = classLoader.loadClass("scala.tools.nsc.ScalaDoc")
                val scaladocMethod = scaladocClass.getMethod("process", classOf[Array[String]])
                val args = Array[String](
                  "-d",
                  generatedDir.toString,
                  "-classpath",
                  compileClasspath.mkString(File.pathSeparator),
                  "--"
                ) ++ sourceFiles.filter(os.isFile(_)).map(_.toString)
                val scaladocObj = scaladocClass.getConstructor().newInstance()
                scaladocMethod.invoke(scaladocObj, args)
              }
            }
          case _ =>
            val javadocTool = ToolProvider.getSystemDocumentationTool
            val outStream = new java.io.ByteArrayOutputStream()
            val args = Array(
              "-classpath",
              compileClasspath.mkString(File.pathSeparator),
              "-d",
              generatedDir.toString
            ) ++ sourceFiles.filter(_.ext == "java").map(_.toString)
            javadocTool.run(null, outStream, outStream, args*)
        }

        val resultJarPath = ctx.out / s"${pomSettings.artifactId}-javadoc.jar"
        os.remove(resultJarPath)
        os.zip(resultJarPath, Seq(generatedDir))
        resultJarPath
      }
    }

  case class PublishArtifactsRes(
      pom: PomSettings,
      outDir: os.Path
  ) derives JsonRW

  val publishArtifactsTask = CachedTaskBuilder
    .make[Option[PublishArtifactsRes]](
      name = "publishArtifacts"
    )
    .dependsOn(scalaVersionTask)
    .dependsOn(pomSettingsTask)
    .dependsOn(moduleDepsPomSettingsTask)
    .dependsOn(mandatoryDependenciesTask)
    .dependsOn(dependenciesTask)
    .dependsOn(jarTask)
    .dependsOn(sourcesJarTask)
    .dependsOn(javadocJarTask)
    .build { ctx =>
      val (
        scalaVersion,
        pomOpt,
        moduleDepsPomSettings,
        mandatoryDependencies,
        dependencies,
        jar,
        sourcesJarOpt,
        javadocJarOpt
      ) = ctx.depResults
      pomOpt.zip(sourcesJarOpt).zip(javadocJarOpt).map { case ((pom, sourcesJar), javadocJar) =>
        val artifactBaseName = s"${pom.artifactId}-${pom.version}"
        os.remove.all(ctx.out)
        os.makeDir.all(ctx.out)
        os.copy.over(jar, ctx.out / s"${artifactBaseName}.jar")
        os.copy.over(sourcesJar, ctx.out / s"${artifactBaseName}-sources.jar")
        os.copy.over(javadocJar, ctx.out / s"${artifactBaseName}-javadoc.jar")
        val pomSettings = ctx.module match {
          case jm: JavaModule => jm.pomSettings
        }
        val allDependencies = mandatoryDependencies ++ dependencies
        // drop this module's pom settings
        // then take just the first level, direct module dependencies
        val moduleDepsPomSettingsClean = moduleDepsPomSettings.take(2).drop(1).flatten
        val pomXmlContent =
          PomGenerator.generate(
            pom.groupId,
            pom.artifactId,
            pom.version,
            allDependencies,
            pomSettings,
            moduleDepsPomSettingsClean
          )
        val pomXmlPath = ctx.out / s"${artifactBaseName}.pom"
        os.write.over(pomXmlPath, pomXmlContent)
        PublishArtifactsRes(pom, ctx.out)
      }
    }

  val publishLocalTask = TaskBuilder
    .make[Option[os.Path]](
      name = "publishLocal"
    )
    .dependsOn(publishArtifactsTask)
    .build { ctx =>
      val publishArtifactsResOpt = ctx.depResults._1
      publishArtifactsResOpt.map { publishArtifactsRes =>
        val pom = publishArtifactsRes.pom
        val artifacts = os.list(publishArtifactsRes.outDir)
        // generate hashes
        val allFiles = artifacts.flatMap { f =>
          Seq(f) ++ Hasher.generateChecksums(f)
        }
        ctx.module match {
          case javaModule: JavaModule =>
            if javaModule.publish then {
              val publisher = Publisher(ctx.notifications, ctx.module.id)
              publisher.publishLocalM2(pom, allFiles)
            } else {
              ctx.notifications.add(
                ServerNotification
                  .logInfo(s"Skipping ${ctx.module.id} publishing because it is disabled", ctx.module.id)
              )
            }
          case _ =>
        }
        ctx.out
      }
    }

  val publishTask = TaskBuilder
    .make[String](
      name = "publish"
    )
    .dependsOn(publishArtifactsTask)
    .build { ctx =>
      val publishArtifactsResOpt = ctx.depResults._1
      publishArtifactsResOpt.map { publishArtifactsRes =>
        val pom = publishArtifactsRes.pom
        val artifacts = os.list(publishArtifactsRes.outDir)
        // sign files
        val pgpPassphrase =
          sys.env.getOrElse("DEDER_PGP_PASSPHRASE", throw RuntimeException("DEDER_PGP_PASSPHRASE env var not set"))
        val pgpSecret =
          sys.env.getOrElse("DEDER_PGP_SECRET", throw RuntimeException("DEDER_PGP_SECRET env var not set"))
        artifacts.foreach(f => PgpSigner.signFile(f, pgpSecret, pgpPassphrase.toCharArray))
        // generate hashes
        val allFiles = artifacts.flatMap { f =>
          val checksumFile = f / os.up / s"${f.last}.asc"
          Seq(f, checksumFile) ++
            Hasher.generateChecksums(f) ++
            Hasher.generateChecksums(checksumFile)
        }
        val username =
          sys.env.getOrElse(
            "DEDER_SONATYPE_USERNAME",
            throw RuntimeException("DEDER_SONATYPE_USERNAME env var not set")
          )
        val password =
          sys.env.getOrElse(
            "DEDER_SONATYPE_PASSWORD",
            throw RuntimeException("DEDER_SONATYPE_PASSWORD env var not set")
          )
        os.remove.all(ctx.out)
        val filesDir =
          ctx.out / "final" / os.SubPath(s"${pom.groupId.replace('.', '/')}/${pom.artifactId}/${pom.version}")
        os.makeDir.all(filesDir)
        allFiles.foreach(f => os.copy(f, filesDir / f.last))
        val filesZip = ctx.out / s"${pom.artifactId}_bundle.zip"
        os.zip(filesZip, Seq(ctx.out / "final"))
        val publisher = Publisher(ctx.notifications, ctx.module.id)
        if pom.version.endsWith("-SNAPSHOT") then publisher.publishSonatypeSnapshot(username, password, pom, allFiles)
        else publisher.publishSonatypeCentral(username, password, pom, filesZip)
      }
      ""
    }

  // order matters for dependency resolution!!
  val all: Seq[Task[?, ?]] = Seq(
    sourcesTask,
    generatedSourcesTask,
    javaHomeTask,
    javaVersionTask,
    scalaVersionTask,
    resourcesTask,
    javacOptionsTask,
    scalacOptionsTask,
    javaSemanticdbVersionTask,
    scalaSemanticdbVersionTask,
    javacAnnotationProcessorDepsTask,
    scalacPluginDepsTask,
    javacAnnotationProcessorsTask,
    scalacPluginsTask,
    depsTask,
    mandatoryDependenciesTask,
    dependenciesTask,
    allDependenciesTask,
    classesTask,
    semanticdbDirTask,
    allClassesDirsTask,
    compilerDepsTask,
    compileClasspathTask,
    compileTask,
    compileBspTask,
    jvmOptionsTask,
    runClasspathTask,
    mainClassTask,
    manifestSettingsTask,
    mainClassesTask,
    finalMainClassTask,
    runTask,
    runMainTask,
    runMvnAppTask,
    fixTask,
    fixCheckTask,
    testClassesTask,
    testTask,
    pomSettingsTask,
    finalManifestSettingsTask,
    jarTask,
    allJarsTask,
    assemblyTask,
    moduleDepsPomSettingsTask,
    sourcesJarTask,
    javadocJarTask,
    publishArtifactsTask,
    publishLocalTask,
    publishTask
  )

}
