#Java mappings for Pkl module `ba.sake.deder.examples.plugins.hello`
#Wed May 13 12:03:13 CEST 2026
org.pkl.config.java.mapper.ba.sake.deder.examples.plugins.hello\#HelloPlugin=ba.sake.deder.examples.plugins.Hello$HelloPlugin
org.pkl.config.java.mapper.ba.sake.deder.examples.plugins.hello\#HelloPluginConfig=ba.sake.deder.examples.plugins.Hello$HelloPluginConfig
org.pkl.config.java.mapper.ba.sake.deder.examples.plugins.hello\#ModuleClass=ba.sake.deder.examples.plugins.Hello
