name: Early Access

on:
  workflow_run:
    workflows: ["ci"]
    branches: [main]
    types: 
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

env:
  JAVA_VERSION: '21'
  JAVA_DISTRO: 'zulu'

jobs:
  precheck:
    if: ${{ github.event.workflow_run.conclusion == 'success' }} && github.repository == 'sake92/deder' && startsWith(github.event.head_commit.message, 'Releasing version') != true
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.vars.outputs.VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRO }}
      - name: Version
        id: vars
        shell: bash
        run: |
          VERSION=$(./mill show server.version | tr -d '"')
          echo "VERSION=$(echo $VERSION)" >> $GITHUB_OUTPUT

  build-cli-native-image:
    needs: [ precheck ]
    if: endsWith(${{ needs.precheck.outputs.VERSION }}, '-SNAPSHOT')
    strategy:
      matrix:
        os:
          - gh-name: ubuntu-22.04
            name: linux-x86_64
            ext: ""
          - gh-name: macos-15
            name: macos-aarch64
            ext: ""
         # - gh-name: windows-2025
         #   name: windows-x86_64
         #   ext: ".exe"
    runs-on: ${{ matrix.os.gh-name }}
    steps:
      - uses: actions/checkout@v4
      - name: Build CLI native image
        run: |
          ./mill -i client-native.nativeImage
          ls out/client-native/nativeImage.dest/
          cp out/client-native/nativeImage.dest/native-executable${{ matrix.os.ext }} deder-${{ matrix.os.name }}${{ matrix.os.ext }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: deder-cli-${{ matrix.os.name }}
          path: deder${{ matrix.os.name }}${{ matrix.os.ext }}

  # TODO download native artifacts
  release:
    needs: [ precheck ]
    if: endsWith(${{ needs.precheck.outputs.VERSION }}, '-SNAPSHOT')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRO }}
      - name: Build JARs
        run: |
          ./scripts/gen-config-bindings.sh
          ./mill server.assembly
          cp out/server/assembly.dest/out.jar deder-server.jar
          ./mill client.assembly
          cp out/client/assembly.dest/out.jar deder-client.jar

      - name: Release
        uses: jreleaser/release-action@v2
        with:
          arguments: full-release
        env:
          JRELEASER_PROJECT_VERSION: ${{ needs.precheck.outputs.VERSION }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          JRELEASER_HOMEBREW_GITHUB_TOKEN: ${{ secrets.JRELEASER_HOMEBREW_GITHUB_TOKEN }}
      - name: JReleaser output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jreleaser-release
          path: |
            out/jreleaser/trace.log
            out/jreleaser/output.properties