name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (no v prefix!, e.g. 1.2.3)'
        required: true

permissions:
  contents: write

env:
  JAVA_VERSION: '21'
  JAVA_DISTRO: 'zulu'

jobs:
  precheck:
    name: Precheck
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.vars.outputs.VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Version
        id: vars
        shell: bash
        run: |
          VERSION="${{ github.event.inputs.version }}"
          echo "VERSION=$(echo $VERSION)" >> $GITHUB_OUTPUT
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Action"
          git commit -a --allow-empty -m "Releasing version $VERSION"
          git push origin main

  build-jars:
    needs: [ precheck ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRO }}
      - uses: coursier/cache-action@v7
        with:
          extraFiles: deder.pkl
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@main
      - name: Install deder
        run: brew install sake92/tap/deder
      - name: Build JARs
        env:
          VERSION: ${{ needs.precheck.outputs.VERSION }}
        run: |
          ./scripts/gen-config-bindings.sh
          mkdir -p client/resources/ba/sake/deder/client
          echo "version=${{ needs.precheck.outputs.VERSION }}" > client/resources/ba/sake/deder/client/version.properties
          deder exec -t assembly -m server -m client -m test-runner
          cp .deder/out/server/assembly/out.jar deder-server.jar
          cp .deder/out/client/assembly/out.jar deder-client.jar
          cp .deder/out/test-runner/assembly/out.jar deder-test-runner.jar
      - name: Upload JARs
        uses: actions/upload-artifact@v4
        with:
          name: deder-jars
          path: |
            deder-server.jar
            deder-test-runner.jar
            deder-client.jar

  build-client-native-image:
    needs: [ precheck ]
    strategy:
      matrix:
        os:
          - gh-name: ubuntu-22.04
            name: linux-x86_64
            ext: ""
          - gh-name: macos-15
            name: osx-aarch_64
            ext: ""
          - gh-name: windows-2025
            name: windows-x86_64
            ext: ".exe"
    runs-on: ${{ matrix.os.gh-name }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '25'
          distribution: 'graalvm-community'
      - uses: coursier/cache-action@v7
        with:
          extraFiles: deder.pkl
      - name: Set up Homebrew
        if: runner.os != 'Windows'
        uses: Homebrew/actions/setup-homebrew@main
      - name: Install deder (brew)
        if: runner.os != 'Windows'
        run: brew install sake92/tap/deder
      - name: Set up Scoop
        if: runner.os == 'Windows'
        uses: MinoruSekine/setup-scoop@v4.0.2
      - name: Install deder (scoop)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          scoop bucket add sake92 https://github.com/sake92/scoop-bucket.git
          scoop install deder
      - name: Build Client native image
        env:
          VERSION: ${{ needs.precheck.outputs.VERSION }}
        run: |
          mkdir -p client/resources/ba/sake/deder/client
          echo "version=${{ needs.precheck.outputs.VERSION }}" > client/resources/ba/sake/deder/client/version.properties
          deder exec -t graalvmNativeImage -m client
          cp .deder/out/client/graalvmNativeImage/native-executable${{ matrix.os.ext }} deder-client-${{ matrix.os.name }}${{ matrix.os.ext }}
      # if windows: rename to deder.exe and zip
      - name: Zip Windows executable
        if: ${{ matrix.os.name == 'windows-x86_64' }}
        shell: pwsh
        run: |
          Rename-Item deder-client-${{ matrix.os.name }}${{ matrix.os.ext }} deder${{ matrix.os.ext }}
          Compress-Archive deder${{ matrix.os.ext }} deder-client-${{ matrix.os.name }}.zip
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: deder-client-${{ matrix.os.name }}
          path: deder-client-${{ matrix.os.name }}*

  release:
    needs: [ precheck, build-jars, build-client-native-image ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRO }}
      - uses: coursier/cache-action@v7
        with:
          extraFiles: deder.pkl
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: deder-*
          merge-multiple: true
          path: .
      - name: Release
        uses: jreleaser/release-action@v2
        with:
          arguments: full-release
        env:
          JRELEASER_PROJECT_VERSION: ${{ needs.precheck.outputs.VERSION }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          JRELEASER_HOMEBREW_GITHUB_TOKEN: ${{ secrets.JRELEASER_HOMEBREW_GITHUB_TOKEN }}
          JRELEASER_SCOOP_GITHUB_TOKEN: ${{ secrets.JRELEASER_SCOOP_GITHUB_TOKEN }}
          JRELEASER_WINGET_GITHUB_TOKEN: ${{ secrets.JRELEASER_WINGET_GITHUB_TOKEN }}
      - name: JReleaser output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jreleaser-release
          path: |
            out/jreleaser/trace.log
            out/jreleaser/output.properties

